name: camera2_flutter_demo
description: "A demo for camera2 library in Flutter."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  material_symbols_icons: ^4.2906.0
  google_fonts: ^8.0.2
  cambrian_camera:
    path: packages/cambrian_camera

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
