// Copyright (c) 2025 Cambrian. All rights reserved.
// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.cambrian.camera

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Typed error codes for camera errors delivered via [CameraFlutterApi.onError].
 *
 * Values are serialized as integer indices — do NOT reorder or insert in the
 * middle; only append before [unknown] to preserve wire compatibility.
 */
enum class CamErrorCode(val raw: Int) {
  CAMERA_DEVICE(0),
  CAMERA_SERVICE(1),
  CAMERA_DISCONNECTED(2),
  CONFIGURATION_FAILED(3),
  PERMISSION_DENIED(4),
  CAMERA_DISABLED(5),
  MAX_CAMERAS_IN_USE(6),
  CAMERA_IN_USE(7),
  CAMERA_ACCESS_ERROR(8),
  MAX_RETRIES_EXCEEDED(9),
  PREVIEW_SURFACE_LOST(10),
  PIPELINE_ERROR(11),
  SETTINGS_CONFLICT(12),
  FRAME_STALL(13),
  CAPTURE_FAILURE(14),
  FPS_DEGRADED(15),
  AE_CONVERGENCE_TIMEOUT(16),
  RECORDING_TRUNCATED(17),
  UNKNOWN(18);

  companion object {
    fun ofRaw(raw: Int): CamErrorCode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CamSize (
  val width: Long,
  val height: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CamSize {
      val width = pigeonVar_list[0] as Long
      val height = pigeonVar_list[1] as Long
      return CamSize(width, height)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      width,
      height,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CamSettings (
  /** "auto" | "manual" | null (don't change). */
  val isoMode: String? = null,
  /** Sensor sensitivity value when isoMode == "manual". */
  val iso: Long? = null,
  /** "auto" | "manual" | null (don't change). */
  val exposureMode: String? = null,
  /** Exposure duration in nanoseconds when exposureMode == "manual". */
  val exposureTimeNs: Long? = null,
  /** "auto" | "manual" | null (don't change). */
  val focusMode: String? = null,
  /** Focus distance in diopters when focusMode == "manual". */
  val focusDistanceDiopters: Double? = null,
  /** "auto" | "locked" | "manual" | null (don't change). */
  val wbMode: String? = null,
  /** Red gain multiplier when wbMode == "manual". */
  val wbGainR: Double? = null,
  /** Green gain multiplier when wbMode == "manual". */
  val wbGainG: Double? = null,
  /** Blue gain multiplier when wbMode == "manual". */
  val wbGainB: Double? = null,
  /** Zoom ratio (1.0 = no zoom). Null = don't change. */
  val zoomRatio: Double? = null,
  /** Camera2 NOISE_REDUCTION_MODE_* constant. Null = don't change. */
  val noiseReductionMode: Long? = null,
  /** Camera2 EDGE_MODE_* constant. Null = don't change. */
  val edgeMode: Long? = null,
  /**
   * Exposure compensation in AE steps. Null = don't change.
   * NOTE: has no effect when isoMode == "manual" or exposureMode == "manual"
   * because CONTROL_AE_MODE is set to OFF in that case.
   */
  val evCompensation: Long? = null,
  /** Enable GPU natural (unprocessed/passthrough) stream. Null = don't change. */
  val enableNaturalStream: Boolean? = null,
  /** Requested height of the GPU natural stream in pixels. Null = don't change. 0 = use default. */
  val naturalStreamHeight: Long? = null,
  /**
   * Center-crop the GPU output to this exact pixel size.
   *
   * When set, the GPU fragment shader samples from the centered
   * sub-rectangle of the configured stream, and the output FBO/PBO/preview
   * buffers are resized to these dims. All downstream consumers — preview
   * surface, raw stream, 480p C++ sink, `captureImage()`, video recording —
   * receive frames at the cropped dims. The camera session stays at full
   * sensor resolution (no Camera2 reconfigure, no `SCALER_CROP_REGION`).
   *
   * Null = "don't change the current crop" (matches the latest-value-wins
   * semantics of the other CamSettings fields). To CLEAR an active crop,
   * send `cropOutputSize` equal to the current sensor stream dims. The
   * Kotlin side detects that output == source and removes the crop,
   * restoring full-sensor output without a Camera2 session restart.
   * The initial state before any crop has been set is "no crop".
   *
   * Constraints (enforced on the Kotlin side; caller receives
   * `FlutterError("invalid_crop", ...)` on violation):
   *   - `0 < width  <= streamWidth`
   *   - `0 < height <= streamHeight`
   *   - `width  % 2 == 0` (GPU/PBO/encoder alignment)
   *   - `height % 2 == 0`
   *
   * Aspect ratio is NOT constrained: cropping a 4160×3120 stream to
   * 1920×1080 is a valid request and produces a symmetric
   * letterbox-style center crop.
   *
   * **Interaction with `zoomRatio`:** zoom and crop compose
   * multiplicatively. The ISP delivers a zoomed full-resolution frame to
   * the GPU, which then center-crops it. Effective zoom from the caller's
   * perspective is approximately `zoomRatio × (streamWidth / cropWidth)`.
   *
   * **Interaction with `captureNaturalPicture()`:** that method
   * intentionally ignores `cropOutputSize` and always returns the
   * full-sensor hardware JPEG. Use `captureImage()` if you want the
   * cropped image.
   */
  val cropOutputSize: CamSize? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CamSettings {
      val isoMode = pigeonVar_list[0] as String?
      val iso = pigeonVar_list[1] as Long?
      val exposureMode = pigeonVar_list[2] as String?
      val exposureTimeNs = pigeonVar_list[3] as Long?
      val focusMode = pigeonVar_list[4] as String?
      val focusDistanceDiopters = pigeonVar_list[5] as Double?
      val wbMode = pigeonVar_list[6] as String?
      val wbGainR = pigeonVar_list[7] as Double?
      val wbGainG = pigeonVar_list[8] as Double?
      val wbGainB = pigeonVar_list[9] as Double?
      val zoomRatio = pigeonVar_list[10] as Double?
      val noiseReductionMode = pigeonVar_list[11] as Long?
      val edgeMode = pigeonVar_list[12] as Long?
      val evCompensation = pigeonVar_list[13] as Long?
      val enableNaturalStream = pigeonVar_list[14] as Boolean?
      val naturalStreamHeight = pigeonVar_list[15] as Long?
      val cropOutputSize = pigeonVar_list[16] as CamSize?
      return CamSettings(isoMode, iso, exposureMode, exposureTimeNs, focusMode, focusDistanceDiopters, wbMode, wbGainR, wbGainG, wbGainB, zoomRatio, noiseReductionMode, edgeMode, evCompensation, enableNaturalStream, naturalStreamHeight, cropOutputSize)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isoMode,
      iso,
      exposureMode,
      exposureTimeNs,
      focusMode,
      focusDistanceDiopters,
      wbMode,
      wbGainR,
      wbGainG,
      wbGainB,
      zoomRatio,
      noiseReductionMode,
      edgeMode,
      evCompensation,
      enableNaturalStream,
      naturalStreamHeight,
      cropOutputSize,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CamProcessingParams (
  val blackR: Double,
  val blackG: Double,
  val blackB: Double,
  val gamma: Double,
  val brightness: Double,
  val contrast: Double,
  val saturation: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CamProcessingParams {
      val blackR = pigeonVar_list[0] as Double
      val blackG = pigeonVar_list[1] as Double
      val blackB = pigeonVar_list[2] as Double
      val gamma = pigeonVar_list[3] as Double
      val brightness = pigeonVar_list[4] as Double
      val contrast = pigeonVar_list[5] as Double
      val saturation = pigeonVar_list[6] as Double
      return CamProcessingParams(blackR, blackG, blackB, gamma, brightness, contrast, saturation)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      blackR,
      blackG,
      blackB,
      gamma,
      brightness,
      contrast,
      saturation,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CamCapabilities (
  /** All supported YUV_420_888 stream resolutions, sorted descending by area. */
  val supportedSizes: List<CamSize>,
  val isoMin: Long,
  val isoMax: Long,
  val exposureTimeMinNs: Long,
  val exposureTimeMaxNs: Long,
  val focusMin: Double,
  val focusMax: Double,
  val zoomMin: Double,
  val zoomMax: Double,
  val evCompMin: Long,
  val evCompMax: Long,
  val evCompensationStep: Double,
  /**
   * Flutter texture ID for the GPU natural stream (passthrough, no color adjustments).
   * 0 if natural stream is disabled.
   */
  val naturalStreamTextureId: Long,
  /** Actual computed width of the GPU natural stream (pixels). 0 if natural stream is disabled. */
  val naturalStreamWidth: Long,
  /** Requested height of the GPU natural stream (pixels). 0 if natural stream is disabled. */
  val naturalStreamHeight: Long,
  /**
   * Flutter texture ID for the GPU processed (tone-mapped) stream — the lane
   * with black-balance/brightness/contrast/saturation/gamma applied. Minted at
   * [CameraHostApi.open] and stable for the session.
   *
   * On Android this equals the camera handle (the handle is the processed
   * `SurfaceProducer.id()`); on iOS the handle and texture IDs come from
   * separate registries, so this is the only authoritative source for the
   * processed lane's texture ID. Mirrors [CamStreamConfiguration.previewTextureId].
   */
  val previewTextureId: Long,
  /** Width of the GPU processed stream texture (pixels). Matches the largest 4:3 YUV size. */
  val streamWidth: Long,
  /** Height of the GPU processed stream texture (pixels). */
  val streamHeight: Long,
  /**
   * Width of the camera session's YUV stream (the actual sensor output
   * before any GPU crop). Unlike [streamWidth], this does NOT change when
   * [CamSettings.cropOutputSize] is active — it always reports the
   * Camera2 session's configured output size.
   */
  val sensorStreamWidth: Long,
  /** Height of the camera session's YUV stream. See [sensorStreamWidth]. */
  val sensorStreamHeight: Long,
  /**
   * Pixel format of the lane buffers exposed via the texture bridge.
   * Values: "BGRA8" (iOS default + Android post-D-2P-09 swizzle),
   * "RGBA16F" (iOS opt-out via OpenConfiguration.lanesEightBit: false),
   * "RGBA8" (Android pre-D-2P-09 — should not be observed in shipped builds).
   * Informational for non-Texture-widget consumers that read buffers raw.
   */
  val streamPixelFormat: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CamCapabilities {
      val supportedSizes = pigeonVar_list[0] as List<CamSize>
      val isoMin = pigeonVar_list[1] as Long
      val isoMax = pigeonVar_list[2] as Long
      val exposureTimeMinNs = pigeonVar_list[3] as Long
      val exposureTimeMaxNs = pigeonVar_list[4] as Long
      val focusMin = pigeonVar_list[5] as Double
      val focusMax = pigeonVar_list[6] as Double
      val zoomMin = pigeonVar_list[7] as Double
      val zoomMax = pigeonVar_list[8] as Double
      val evCompMin = pigeonVar_list[9] as Long
      val evCompMax = pigeonVar_list[10] as Long
      val evCompensationStep = pigeonVar_list[11] as Double
      val naturalStreamTextureId = pigeonVar_list[12] as Long
      val naturalStreamWidth = pigeonVar_list[13] as Long
      val naturalStreamHeight = pigeonVar_list[14] as Long
      val previewTextureId = pigeonVar_list[15] as Long
      val streamWidth = pigeonVar_list[16] as Long
      val streamHeight = pigeonVar_list[17] as Long
      val sensorStreamWidth = pigeonVar_list[18] as Long
      val sensorStreamHeight = pigeonVar_list[19] as Long
      val streamPixelFormat = pigeonVar_list[20] as String
      return CamCapabilities(supportedSizes, isoMin, isoMax, exposureTimeMinNs, exposureTimeMaxNs, focusMin, focusMax, zoomMin, zoomMax, evCompMin, evCompMax, evCompensationStep, naturalStreamTextureId, naturalStreamWidth, naturalStreamHeight, previewTextureId, streamWidth, streamHeight, sensorStreamWidth, sensorStreamHeight, streamPixelFormat)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      supportedSizes,
      isoMin,
      isoMax,
      exposureTimeMinNs,
      exposureTimeMaxNs,
      focusMin,
      focusMax,
      zoomMin,
      zoomMax,
      evCompMin,
      evCompMax,
      evCompensationStep,
      naturalStreamTextureId,
      naturalStreamWidth,
      naturalStreamHeight,
      previewTextureId,
      streamWidth,
      streamHeight,
      sensorStreamWidth,
      sensorStreamHeight,
      streamPixelFormat,
    )
  }
}

/**
 * Lean payload for the active stream-configuration change callback.
 *
 * Emitted on the active selection changing (after [CameraHostApi.setResolution]
 * resolves or after [CamSettings.cropOutputSize] is set/cleared) — distinct
 * from the heavier [CamCapabilities] which is a one-time bootstrap surface
 * retrieved via [CameraHostApi.getCapabilities].
 *
 * The texture-ID fields ([naturalTextureId], [previewTextureId]) are stable
 * across the open session — they are minted at [CameraHostApi.open] time and
 * carried on every change emission so a Dart consumer never needs a
 * separate getCapabilities round-trip after a configuration change.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CamStreamConfiguration (
  /** Width of the active capture stream (sensor output before any GPU crop). */
  val captureWidth: Long,
  /** Height of the active capture stream. */
  val captureHeight: Long,
  /** Width of the active GPU center crop. Null = no crop (full capture). */
  val cropWidth: Long? = null,
  /** Height of the active GPU center crop. Null = no crop (full capture). */
  val cropHeight: Long? = null,
  /** Flutter texture ID for the natural-stream lane. Stable across the open session. */
  val naturalTextureId: Long,
  /**
   * Flutter texture ID for the processed (post-color-pipeline) preview lane.
   * Stable across the open session.
   */
  val previewTextureId: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CamStreamConfiguration {
      val captureWidth = pigeonVar_list[0] as Long
      val captureHeight = pigeonVar_list[1] as Long
      val cropWidth = pigeonVar_list[2] as Long?
      val cropHeight = pigeonVar_list[3] as Long?
      val naturalTextureId = pigeonVar_list[4] as Long
      val previewTextureId = pigeonVar_list[5] as Long
      return CamStreamConfiguration(captureWidth, captureHeight, cropWidth, cropHeight, naturalTextureId, previewTextureId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      captureWidth,
      captureHeight,
      cropWidth,
      cropHeight,
      naturalTextureId,
      previewTextureId,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CamStateUpdate (
  /**
   * One of: "closed", "opening", "streaming", "recovering", "paused", "error",
   * "interrupted".
   *
   * - "paused" — pipeline gate closed because the app is not foreground
   *   (scene phase inactive/background); resumes automatically when the app
   *   becomes active. Driven natively by the plugin's scene-lifecycle
   *   observer, not by Dart.
   * - "interrupted" — iOS-only — AVCaptureSession was interrupted by a
   *   routine iOS event (Control Center claim, Split View / Stage Manager
   *   peer, phone call). Auto-resumes when the system clears the
   *   interruption; not an error.
   * - "error" — fatal or recoverable hardware/configuration error; see
   *   `onError` for code + isFatal.
   *
   * Android never emits "interrupted" (no equivalent route on the platform).
   * All other values are emitted on both platforms.
   */
  val state: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CamStateUpdate {
      val state = pigeonVar_list[0] as String
      return CamStateUpdate(state)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      state,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CamError (
  val code: CamErrorCode,
  val message: String,
  val isFatal: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CamError {
      val code = pigeonVar_list[0] as CamErrorCode
      val message = pigeonVar_list[1] as String
      val isFatal = pigeonVar_list[2] as Boolean
      return CamError(code, message, isFatal)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      code,
      message,
      isFatal,
    )
  }
}

/**
 * Actual sensor values reported by the hardware after each captured frame.
 *
 * All fields are nullable — null means the hardware did not report that value.
 * Delivered via [CameraFlutterApi.onFrameResult] at ~3 Hz (every 10th frame).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CamFrameResult (
  /** Actual sensor sensitivity (ISO) used for this frame. */
  val iso: Long? = null,
  /** Actual exposure duration in nanoseconds used for this frame. */
  val exposureTimeNs: Long? = null,
  /** Actual focus distance in diopters (1/metres). 0.0 = infinity. */
  val focusDistanceDiopters: Double? = null,
  /** Red channel gain from COLOR_CORRECTION_GAINS. */
  val wbGainR: Double? = null,
  /** Green channel gain (average of greenEven + greenOdd). */
  val wbGainG: Double? = null,
  /** Blue channel gain from COLOR_CORRECTION_GAINS. */
  val wbGainB: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CamFrameResult {
      val iso = pigeonVar_list[0] as Long?
      val exposureTimeNs = pigeonVar_list[1] as Long?
      val focusDistanceDiopters = pigeonVar_list[2] as Double?
      val wbGainR = pigeonVar_list[3] as Double?
      val wbGainG = pigeonVar_list[4] as Double?
      val wbGainB = pigeonVar_list[5] as Double?
      return CamFrameResult(iso, exposureTimeNs, focusDistanceDiopters, wbGainR, wbGainG, wbGainB)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      iso,
      exposureTimeNs,
      focusDistanceDiopters,
      wbGainR,
      wbGainG,
      wbGainB,
    )
  }
}

/**
 * Mean R, G, B from a sampled image patch. All values in [0.0, 1.0].
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CamRgbSample (
  val r: Double,
  val g: Double,
  val b: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CamRgbSample {
      val r = pigeonVar_list[0] as Double
      val g = pigeonVar_list[1] as Double
      val b = pigeonVar_list[2] as Double
      return CamRgbSample(r, g, b)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      r,
      g,
      b,
    )
  }
}

/**
 * Result of an iOS-engine calibration call ([CameraHostApi.calibrateWhiteBalance]
 * / [CameraHostApi.calibrateBlackBalance]).
 *
 * Spec source: `docs/superpowers/specs/2026-05-18-phase-3-design.md`
 * §6.1 + CameraKit/DECISIONS.md D-2P-02. The four required fields
 * (`before`, `after`, `converged`, `iterations`) mirror the iOS
 * engine's `CalibrationResult`; for the Phase-2 single-shot iOS
 * algorithm `converged` is always true and `iterations` is always 1.
 *
 * The six optional fields below carry the engine's *committed* values
 * so the Dart-side caller can populate the existing
 * `WbCalibrationResult.gains` / `BbCalibrationResult.offsets` records.
 * Dart consumers immediately re-apply those values to the camera
 * after calibration (see example app in
 * `lib/main.dart:_runWbCalibration` / `_runBbCalibration`), so they
 * must be the *real* committed values, not sentinels. The iOS adapter
 * reads them from `CameraEngine.currentSettingsSnapshot()` /
 * `currentProcessingParametersSnapshot()` immediately after the
 * engine's calibration call returns.
 *
 * Field nullability mirrors which method produced the result:
 *   - `calibrateWhiteBalance` populates `gainR/G/B`; black fields null.
 *   - `calibrateBlackBalance` populates `blackR/G/B`; gain fields null.
 *
 * Android does not invoke these methods — the Kotlin plugin's stubs
 * throw `FlutterError("not_implemented", ...)`. The Dart-side
 * `CambrianCamera.calibrateWhiteBalance` / `calibrateBlackBalance`
 * branches on `Platform.isIOS` before invoking, so on Android these
 * methods are unreachable.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CamCalibrationResult (
  /** RGB sample of the center patch before the calibration was applied. */
  val before: CamRgbSample,
  /** RGB sample of the center patch after the calibration was applied. */
  val after: CamRgbSample,
  /** Whether the algorithm converged. Always true for the Phase-2 single-shot iOS path. */
  val converged: Boolean,
  /** Iteration count. Always 1 for the Phase-2 single-shot iOS path. */
  val iterations: Long,
  /** WB-only — committed red-channel gain after `calibrateWhiteBalance`. Null for BB. */
  val gainR: Double? = null,
  /** WB-only — committed green-channel gain after `calibrateWhiteBalance`. Null for BB. */
  val gainG: Double? = null,
  /** WB-only — committed blue-channel gain after `calibrateWhiteBalance`. Null for BB. */
  val gainB: Double? = null,
  /** BB-only — committed red-channel black-level offset after `calibrateBlackBalance`. Null for WB. */
  val blackR: Double? = null,
  /** BB-only — committed green-channel black-level offset after `calibrateBlackBalance`. Null for WB. */
  val blackG: Double? = null,
  /** BB-only — committed blue-channel black-level offset after `calibrateBlackBalance`. Null for WB. */
  val blackB: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CamCalibrationResult {
      val before = pigeonVar_list[0] as CamRgbSample
      val after = pigeonVar_list[1] as CamRgbSample
      val converged = pigeonVar_list[2] as Boolean
      val iterations = pigeonVar_list[3] as Long
      val gainR = pigeonVar_list[4] as Double?
      val gainG = pigeonVar_list[5] as Double?
      val gainB = pigeonVar_list[6] as Double?
      val blackR = pigeonVar_list[7] as Double?
      val blackG = pigeonVar_list[8] as Double?
      val blackB = pigeonVar_list[9] as Double?
      return CamCalibrationResult(before, after, converged, iterations, gainR, gainG, gainB, blackR, blackG, blackB)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      before,
      after,
      converged,
      iterations,
      gainR,
      gainG,
      gainB,
      blackR,
      blackG,
      blackB,
    )
  }
}

/**
 * Destination for image-capture output on iOS Photos / Android MediaStore.
 *
 * When [saveToLibrary] is true: iOS writes through PHPhotoLibrary and yields
 * a PHAsset local identifier (no filesystem path); Android writes through
 * MediaStore and yields a content URI / file path. When false: both
 * platforms write to filesystem at the [CameraHostApi.captureImage]
 * `outputDirectory` + `fileName` arguments and yield the filesystem path.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CamPhotosDestination (
  /** Optional album name on iOS Photos. Ignored on Android. */
  val albumName: String? = null,
  /**
   * If true, save to the platform photo library (Photos / MediaStore).
   * If false, write to filesystem at the host method's outputDirectory + fileName.
   */
  val saveToLibrary: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CamPhotosDestination {
      val albumName = pigeonVar_list[0] as String?
      val saveToLibrary = pigeonVar_list[1] as Boolean
      return CamPhotosDestination(albumName, saveToLibrary)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      albumName,
      saveToLibrary,
    )
  }
}

/**
 * Result of an image capture.
 *
 * One of [filePath] / [phAssetLocalId] is non-null depending on the
 * [CamPhotosDestination.saveToLibrary] flag and platform:
 * - iOS + saveToLibrary == true: [phAssetLocalId] populated; [filePath] null.
 * - iOS + saveToLibrary == false (or null destination): [filePath] populated.
 * - Android (any destination): [filePath] populated; [phAssetLocalId] null.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CamCaptureResult (
  val filePath: String? = null,
  val phAssetLocalId: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CamCaptureResult {
      val filePath = pigeonVar_list[0] as String?
      val phAssetLocalId = pigeonVar_list[1] as String?
      return CamCaptureResult(filePath, phAssetLocalId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      filePath,
      phAssetLocalId,
    )
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CamErrorCode.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CamSize.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CamSettings.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CamProcessingParams.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CamCapabilities.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CamStreamConfiguration.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CamStateUpdate.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CamError.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CamFrameResult.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CamRgbSample.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CamCalibrationResult.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CamPhotosDestination.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CamCaptureResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is CamErrorCode -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is CamSize -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is CamSettings -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is CamProcessingParams -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is CamCapabilities -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is CamStreamConfiguration -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is CamStateUpdate -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is CamError -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is CamFrameResult -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is CamRgbSample -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is CamCalibrationResult -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is CamPhotosDestination -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is CamCaptureResult -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface CameraHostApi {
  fun open(cameraId: String?, settings: CamSettings?, callback: (Result<Long>) -> Unit)
  fun getCapabilities(handle: Long, callback: (Result<CamCapabilities>) -> Unit)
  fun updateSettings(handle: Long, settings: CamSettings)
  fun setResolution(handle: Long, width: Long, height: Long, callback: (Result<Unit>) -> Unit)
  fun setProcessingParams(handle: Long, params: CamProcessingParams)
  /**
   * Captures a still JPEG image using Camera2's hardware ISP (Android) or
   * the natural-lane tap (iOS). Does NOT include GPU post-processing
   * (saturation, contrast, brightness, black balance, gamma).
   *
   * Neutral hardware baseline: captured with auto AE/AWB at 1.0x zoom. Manual
   * ISO/exposure/WB/zoom from [updateSettings] are NOT applied (use captureImage).
   *
   * Returns a [CamCaptureResult] whose populated field depends on
   * [destination] and platform — see [CamPhotosDestination] /
   * [CamCaptureResult] for the per-platform semantics.
   */
  fun captureNaturalPicture(handle: Long, outputDirectory: String?, fileName: String?, destination: CamPhotosDestination?, callback: (Result<CamCaptureResult>) -> Unit)
  /**
   * Captures the next GPU post-processed frame and saves it.
   * Format is inferred from [fileName] extension: .jpg/.jpeg → JPEG (quality 90),
   * .png or absent extension → PNG. [outputDirectory] null = system gallery
   * under Pictures/CambrianCamera (via MediaStore on Android).
   *
   * Returns a [CamCaptureResult] whose populated field depends on
   * [destination] and platform — see [CamPhotosDestination] /
   * [CamCaptureResult] for the per-platform semantics.
   */
  fun captureImage(handle: Long, outputDirectory: String?, fileName: String?, destination: CamPhotosDestination?, callback: (Result<CamCaptureResult>) -> Unit)
  fun getNativePipelineHandle(handle: Long, callback: (Result<Long?>) -> Unit)
  fun startRecording(handle: Long, outputDirectory: String?, fileName: String?, bitrate: Long?, fps: Long?, callback: (Result<String>) -> Unit)
  fun stopRecording(handle: Long, callback: (Result<String>) -> Unit)
  fun close(handle: Long, callback: (Result<Unit>) -> Unit)
  /**
   * Returns persisted processing params from a previous session, or null if none exist.
   *
   * Dart should call this after [open] to initialize slider UI with the user's last-known
   * values instead of sending default zeros that would overwrite the persisted state.
   */
  fun getPersistedProcessingParams(handle: Long): CamProcessingParams?
  /**
   * Samples the center 96×96 pixel patch of the most recent GPU-processed
   * RGBA frame and returns the trimmed-mean R, G, B as values in [0.0, 1.0].
   *
   * Throws with error code "patch_not_ready" if no frame has been rendered yet.
   */
  fun sampleCenterPatch(handle: Long, callback: (Result<CamRgbSample>) -> Unit)
  /**
   * **iOS-only.** Runs the iOS engine's single-shot gray-world
   * white-balance calibration. Wraps `CameraEngine.calibrateWhiteBalance()` —
   * CameraKit/DECISIONS.md D-2P-03, D-2P-05, D-2P-08.
   *
   * On Android this throws `FlutterError("not_implemented", ...)` —
   * the Dart-side `CambrianCamera.calibrateWhiteBalance` controller
   * method branches on `Platform.isIOS` BEFORE invoking, so the
   * Android stub is unreachable in normal use.
   *
   * Throws `PigeonError(code: "calibration_in_progress", ...)` if a
   * calibration is already in flight. Throws
   * `PigeonError(code: "cancelled", ...)` if the in-flight task is
   * cancelled by a lifecycle transition (close / interrupt). Throws
   * `PigeonError(code: "handle_not_found", ...)` if `handle` is not
   * currently registered.
   */
  fun calibrateWhiteBalance(handle: Long, callback: (Result<CamCalibrationResult>) -> Unit)
  /**
   * **iOS-only.** Runs the iOS engine's single-shot black-balance
   * calibration. Wraps `CameraEngine.calibrateBlackBalance()` —
   * CameraKit/DECISIONS.md D-2P-03, D-2P-05, D-2P-08.
   *
   * On Android this throws `FlutterError("not_implemented", ...)`.
   * Throws the same set of `PigeonError` codes as
   * [calibrateWhiteBalance].
   */
  fun calibrateBlackBalance(handle: Long, callback: (Result<CamCalibrationResult>) -> Unit)
  /**
   * Returns the current camera permission status:
   * "notDetermined" | "denied" | "restricted" | "authorized".
   *
   * Callers should query this before invoking [open] so they can present
   * a permission rationale UI rather than discovering denial as an open
   * failure. iOS-style four-value status; Android maps PERMISSION_GRANTED
   * → "authorized", PERMISSION_DENIED → "denied" (or "restricted" if
   * don't-ask-again was selected).
   */
  fun cameraPermissionStatus(callback: (Result<String>) -> Unit)
  /**
   * Triggers the system permission prompt for camera access; returns the
   * resulting status (same four values as [cameraPermissionStatus]).
   *
   * No-op (returns current status) if already authorized.
   */
  fun requestCameraPermission(callback: (Result<String>) -> Unit)
  /**
   * Status query for Photos add-only permission (iOS) or WRITE_EXTERNAL_STORAGE
   * (Android pre-API 29) / no-op (Android API 29+, MediaStore handles it).
   */
  fun photosAddPermissionStatus(callback: (Result<String>) -> Unit)
  /**
   * Trigger Photos add-only permission prompt (iOS) / WRITE_EXTERNAL_STORAGE
   * (Android pre-API 29) / no-op (Android API 29+).
   */
  fun requestPhotosAddPermission(callback: (Result<String>) -> Unit)

  companion object {
    /** The codec used by CameraHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `CameraHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: CameraHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_camera.CameraHostApi.open$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val cameraIdArg = args[0] as String?
            val settingsArg = args[1] as CamSettings?
            api.open(cameraIdArg, settingsArg) { result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_camera.CameraHostApi.getCapabilities$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            api.getCapabilities(handleArg) { result: Result<CamCapabilities> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_camera.CameraHostApi.updateSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val settingsArg = args[1] as CamSettings
            val wrapped: List<Any?> = try {
              api.updateSettings(handleArg, settingsArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_camera.CameraHostApi.setResolution$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val widthArg = args[1] as Long
            val heightArg = args[2] as Long
            api.setResolution(handleArg, widthArg, heightArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_camera.CameraHostApi.setProcessingParams$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val paramsArg = args[1] as CamProcessingParams
            val wrapped: List<Any?> = try {
              api.setProcessingParams(handleArg, paramsArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_camera.CameraHostApi.captureNaturalPicture$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val outputDirectoryArg = args[1] as String?
            val fileNameArg = args[2] as String?
            val destinationArg = args[3] as CamPhotosDestination?
            api.captureNaturalPicture(handleArg, outputDirectoryArg, fileNameArg, destinationArg) { result: Result<CamCaptureResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_camera.CameraHostApi.captureImage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val outputDirectoryArg = args[1] as String?
            val fileNameArg = args[2] as String?
            val destinationArg = args[3] as CamPhotosDestination?
            api.captureImage(handleArg, outputDirectoryArg, fileNameArg, destinationArg) { result: Result<CamCaptureResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_camera.CameraHostApi.getNativePipelineHandle$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            api.getNativePipelineHandle(handleArg) { result: Result<Long?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_camera.CameraHostApi.startRecording$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val outputDirectoryArg = args[1] as String?
            val fileNameArg = args[2] as String?
            val bitrateArg = args[3] as Long?
            val fpsArg = args[4] as Long?
            api.startRecording(handleArg, outputDirectoryArg, fileNameArg, bitrateArg, fpsArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_camera.CameraHostApi.stopRecording$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            api.stopRecording(handleArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_camera.CameraHostApi.close$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            api.close(handleArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_camera.CameraHostApi.getPersistedProcessingParams$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.getPersistedProcessingParams(handleArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_camera.CameraHostApi.sampleCenterPatch$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            api.sampleCenterPatch(handleArg) { result: Result<CamRgbSample> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_camera.CameraHostApi.calibrateWhiteBalance$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            api.calibrateWhiteBalance(handleArg) { result: Result<CamCalibrationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_camera.CameraHostApi.calibrateBlackBalance$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            api.calibrateBlackBalance(handleArg) { result: Result<CamCalibrationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_camera.CameraHostApi.cameraPermissionStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.cameraPermissionStatus{ result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_camera.CameraHostApi.requestCameraPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.requestCameraPermission{ result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_camera.CameraHostApi.photosAddPermissionStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.photosAddPermissionStatus{ result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_camera.CameraHostApi.requestPhotosAddPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.requestPhotosAddPermission{ result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class CameraFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by CameraFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  fun onStateChanged(handleArg: Long, stateArg: CamStateUpdate, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onStateChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(handleArg, stateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String?, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onError(handleArg: Long, errorArg: CamError, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(handleArg, errorArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String?, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onFrameResult(handleArg: Long, resultArg: CamFrameResult, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onFrameResult$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(handleArg, resultArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String?, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /**
   * Called when the recording state changes.
   * [state] is one of: "recording", "idle", "error".
   */
  fun onRecordingStateChanged(handleArg: Long, stateArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onRecordingStateChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(handleArg, stateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String?, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /**
   * Called when the active stream configuration changes — after
   * `cropOutputSize` is set or cleared, or after `setResolution` resolves
   * to a new camera stream size. The payload's texture-ID fields are
   * stable across the open session and are repeated on every change so
   * Dart consumers do not need a separate `getCapabilities` round-trip.
   */
  fun onStreamConfigurationChanged(handleArg: Long, configurationArg: CamStreamConfiguration, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onStreamConfigurationChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(handleArg, configurationArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String?, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
