// Copyright (c) 2025 Cambrian. All rights reserved.
// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.cambrian.camera

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class CamSize (
  val width: Long,
  val height: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CamSize {
      val width = pigeonVar_list[0] as Long
      val height = pigeonVar_list[1] as Long
      return CamSize(width, height)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      width,
      height,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CamSettings (
  val iso: Long? = null,
  val exposureTimeNs: Long? = null,
  val focusDistanceDiopters: Double? = null,
  val zoomRatio: Double? = null,
  val afEnabled: Boolean? = null,
  val awbLocked: Boolean? = null,
  val noiseReductionMode: Long? = null,
  val edgeMode: Long? = null,
  val evCompensation: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CamSettings {
      val iso = pigeonVar_list[0] as Long?
      val exposureTimeNs = pigeonVar_list[1] as Long?
      val focusDistanceDiopters = pigeonVar_list[2] as Double?
      val zoomRatio = pigeonVar_list[3] as Double?
      val afEnabled = pigeonVar_list[4] as Boolean?
      val awbLocked = pigeonVar_list[5] as Boolean?
      val noiseReductionMode = pigeonVar_list[6] as Long?
      val edgeMode = pigeonVar_list[7] as Long?
      val evCompensation = pigeonVar_list[8] as Long?
      return CamSettings(iso, exposureTimeNs, focusDistanceDiopters, zoomRatio, afEnabled, awbLocked, noiseReductionMode, edgeMode, evCompensation)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      iso,
      exposureTimeNs,
      focusDistanceDiopters,
      zoomRatio,
      afEnabled,
      awbLocked,
      noiseReductionMode,
      edgeMode,
      evCompensation,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CamProcessingParams (
  val blackR: Double,
  val blackG: Double,
  val blackB: Double,
  val gamma: Double,
  val histBlackPoint: Double,
  val histWhitePoint: Double,
  val autoStretch: Boolean,
  val autoStretchLow: Double,
  val autoStretchHigh: Double,
  val brightness: Double,
  val saturation: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CamProcessingParams {
      val blackR = pigeonVar_list[0] as Double
      val blackG = pigeonVar_list[1] as Double
      val blackB = pigeonVar_list[2] as Double
      val gamma = pigeonVar_list[3] as Double
      val histBlackPoint = pigeonVar_list[4] as Double
      val histWhitePoint = pigeonVar_list[5] as Double
      val autoStretch = pigeonVar_list[6] as Boolean
      val autoStretchLow = pigeonVar_list[7] as Double
      val autoStretchHigh = pigeonVar_list[8] as Double
      val brightness = pigeonVar_list[9] as Double
      val saturation = pigeonVar_list[10] as Double
      return CamProcessingParams(blackR, blackG, blackB, gamma, histBlackPoint, histWhitePoint, autoStretch, autoStretchLow, autoStretchHigh, brightness, saturation)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      blackR,
      blackG,
      blackB,
      gamma,
      histBlackPoint,
      histWhitePoint,
      autoStretch,
      autoStretchLow,
      autoStretchHigh,
      brightness,
      saturation,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CamCapabilities (
  val supportedSizes: List<CamSize?>,
  val isoMin: Long,
  val isoMax: Long,
  val exposureTimeMinNs: Long,
  val exposureTimeMaxNs: Long,
  val focusMin: Double,
  val focusMax: Double,
  val zoomMin: Double,
  val zoomMax: Double,
  val evCompMin: Long,
  val evCompMax: Long,
  val evCompensationStep: Double,
  val supportsRgba8888: Boolean,
  val estimatedMemoryBytes: Long,
  /** Width of the YUV stream used by the C++ pipeline (pixels). */
  val streamWidth: Long,
  /** Height of the YUV stream used by the C++ pipeline (pixels). */
  val streamHeight: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CamCapabilities {
      val supportedSizes = pigeonVar_list[0] as List<CamSize?>
      val isoMin = pigeonVar_list[1] as Long
      val isoMax = pigeonVar_list[2] as Long
      val exposureTimeMinNs = pigeonVar_list[3] as Long
      val exposureTimeMaxNs = pigeonVar_list[4] as Long
      val focusMin = pigeonVar_list[5] as Double
      val focusMax = pigeonVar_list[6] as Double
      val zoomMin = pigeonVar_list[7] as Double
      val zoomMax = pigeonVar_list[8] as Double
      val evCompMin = pigeonVar_list[9] as Long
      val evCompMax = pigeonVar_list[10] as Long
      val evCompensationStep = pigeonVar_list[11] as Double
      val supportsRgba8888 = pigeonVar_list[12] as Boolean
      val estimatedMemoryBytes = pigeonVar_list[13] as Long
      val streamWidth = pigeonVar_list[14] as Long
      val streamHeight = pigeonVar_list[15] as Long
      return CamCapabilities(supportedSizes, isoMin, isoMax, exposureTimeMinNs, exposureTimeMaxNs, focusMin, focusMax, zoomMin, zoomMax, evCompMin, evCompMax, evCompensationStep, supportsRgba8888, estimatedMemoryBytes, streamWidth, streamHeight)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      supportedSizes,
      isoMin,
      isoMax,
      exposureTimeMinNs,
      exposureTimeMaxNs,
      focusMin,
      focusMax,
      zoomMin,
      zoomMax,
      evCompMin,
      evCompMax,
      evCompensationStep,
      supportsRgba8888,
      estimatedMemoryBytes,
      streamWidth,
      streamHeight,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CamStateUpdate (
  /** One of: "closed", "opening", "streaming", "recovering", "error" */
  val state: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CamStateUpdate {
      val state = pigeonVar_list[0] as String
      return CamStateUpdate(state)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      state,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CamError (
  val code: String,
  val message: String,
  val isFatal: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CamError {
      val code = pigeonVar_list[0] as String
      val message = pigeonVar_list[1] as String
      val isFatal = pigeonVar_list[2] as Boolean
      return CamError(code, message, isFatal)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      code,
      message,
      isFatal,
    )
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CamSize.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CamSettings.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CamProcessingParams.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CamCapabilities.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CamStateUpdate.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CamError.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is CamSize -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is CamSettings -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is CamProcessingParams -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is CamCapabilities -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is CamStateUpdate -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is CamError -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface CameraHostApi {
  fun open(cameraId: String?, settings: CamSettings?, callback: (Result<Long>) -> Unit)
  fun getCapabilities(handle: Long, callback: (Result<CamCapabilities>) -> Unit)
  fun updateSettings(handle: Long, settings: CamSettings)
  fun setProcessingParams(handle: Long, params: CamProcessingParams)
  fun takePicture(handle: Long, callback: (Result<String>) -> Unit)
  fun getNativePipelineHandle(handle: Long, callback: (Result<Long>) -> Unit)
  fun close(handle: Long, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by CameraHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `CameraHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: CameraHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_camera.CameraHostApi.open$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val cameraIdArg = args[0] as String?
            val settingsArg = args[1] as CamSettings?
            api.open(cameraIdArg, settingsArg) { result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_camera.CameraHostApi.getCapabilities$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            api.getCapabilities(handleArg) { result: Result<CamCapabilities> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_camera.CameraHostApi.updateSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val settingsArg = args[1] as CamSettings
            val wrapped: List<Any?> = try {
              api.updateSettings(handleArg, settingsArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_camera.CameraHostApi.setProcessingParams$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val paramsArg = args[1] as CamProcessingParams
            val wrapped: List<Any?> = try {
              api.setProcessingParams(handleArg, paramsArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_camera.CameraHostApi.takePicture$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            api.takePicture(handleArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_camera.CameraHostApi.getNativePipelineHandle$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            api.getNativePipelineHandle(handleArg) { result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_camera.CameraHostApi.close$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            api.close(handleArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class CameraFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by CameraFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  fun onStateChanged(handleArg: Long, stateArg: CamStateUpdate, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onStateChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(handleArg, stateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onError(handleArg: Long, errorArg: CamError, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(handleArg, errorArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
