// Copyright (c) 2025 Cambrian. All rights reserved.
// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.cambrian.camera

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Typed error codes for camera errors delivered via [CameraFlutterApi.onError].
 *
 * Values are serialized as integer indices — do NOT reorder or insert in the
 * middle; only append before [unknown] to preserve wire compatibility.
 */
enum class CamErrorCode(val raw: Int) {
  CAMERA_DEVICE(0),
  CAMERA_SERVICE(1),
  CAMERA_DISCONNECTED(2),
  CONFIGURATION_FAILED(3),
  PERMISSION_DENIED(4),
  CAMERA_DISABLED(5),
  MAX_CAMERAS_IN_USE(6),
  CAMERA_IN_USE(7),
  CAMERA_ACCESS_ERROR(8),
  MAX_RETRIES_EXCEEDED(9),
  PREVIEW_SURFACE_LOST(10),
  PIPELINE_ERROR(11),
  SETTINGS_CONFLICT(12),
  UNKNOWN(13);

  companion object {
    fun ofRaw(raw: Int): CamErrorCode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CamSize (
  val width: Long,
  val height: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CamSize {
      val width = pigeonVar_list[0] as Long
      val height = pigeonVar_list[1] as Long
      return CamSize(width, height)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      width,
      height,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CamSettings (
  /** "auto" | "manual" | null (don't change). */
  val isoMode: String? = null,
  /** Sensor sensitivity value when isoMode == "manual". */
  val iso: Long? = null,
  /** "auto" | "manual" | null (don't change). */
  val exposureMode: String? = null,
  /** Exposure duration in nanoseconds when exposureMode == "manual". */
  val exposureTimeNs: Long? = null,
  /** "auto" | "manual" | null (don't change). */
  val focusMode: String? = null,
  /** Focus distance in diopters when focusMode == "manual". */
  val focusDistanceDiopters: Double? = null,
  /** "auto" | "locked" | "manual" | null (don't change). */
  val wbMode: String? = null,
  /** Red gain multiplier when wbMode == "manual". */
  val wbGainR: Double? = null,
  /** Green gain multiplier when wbMode == "manual". */
  val wbGainG: Double? = null,
  /** Blue gain multiplier when wbMode == "manual". */
  val wbGainB: Double? = null,
  /** Zoom ratio (1.0 = no zoom). Null = don't change. */
  val zoomRatio: Double? = null,
  /** Camera2 NOISE_REDUCTION_MODE_* constant. Null = don't change. */
  val noiseReductionMode: Long? = null,
  /** Camera2 EDGE_MODE_* constant. Null = don't change. */
  val edgeMode: Long? = null,
  /**
   * Exposure compensation in AE steps. Null = don't change.
   * NOTE: has no effect when isoMode == "manual" or exposureMode == "manual"
   * because CONTROL_AE_MODE is set to OFF in that case.
   */
  val evCompensation: Long? = null,
  /** Enable GPU raw (passthrough) stream. Null = don't change. */
  val enableRawStream: Boolean? = null,
  /** Requested height of the GPU raw stream in pixels. Null = don't change. 0 = use default. */
  val rawStreamHeight: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CamSettings {
      val isoMode = pigeonVar_list[0] as String?
      val iso = pigeonVar_list[1] as Long?
      val exposureMode = pigeonVar_list[2] as String?
      val exposureTimeNs = pigeonVar_list[3] as Long?
      val focusMode = pigeonVar_list[4] as String?
      val focusDistanceDiopters = pigeonVar_list[5] as Double?
      val wbMode = pigeonVar_list[6] as String?
      val wbGainR = pigeonVar_list[7] as Double?
      val wbGainG = pigeonVar_list[8] as Double?
      val wbGainB = pigeonVar_list[9] as Double?
      val zoomRatio = pigeonVar_list[10] as Double?
      val noiseReductionMode = pigeonVar_list[11] as Long?
      val edgeMode = pigeonVar_list[12] as Long?
      val evCompensation = pigeonVar_list[13] as Long?
      val enableRawStream = pigeonVar_list[14] as Boolean?
      val rawStreamHeight = pigeonVar_list[15] as Long?
      return CamSettings(isoMode, iso, exposureMode, exposureTimeNs, focusMode, focusDistanceDiopters, wbMode, wbGainR, wbGainG, wbGainB, zoomRatio, noiseReductionMode, edgeMode, evCompensation, enableRawStream, rawStreamHeight)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isoMode,
      iso,
      exposureMode,
      exposureTimeNs,
      focusMode,
      focusDistanceDiopters,
      wbMode,
      wbGainR,
      wbGainG,
      wbGainB,
      zoomRatio,
      noiseReductionMode,
      edgeMode,
      evCompensation,
      enableRawStream,
      rawStreamHeight,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CamProcessingParams (
  val blackR: Double,
  val blackG: Double,
  val blackB: Double,
  val gamma: Double,
  val brightness: Double,
  val contrast: Double,
  val saturation: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CamProcessingParams {
      val blackR = pigeonVar_list[0] as Double
      val blackG = pigeonVar_list[1] as Double
      val blackB = pigeonVar_list[2] as Double
      val gamma = pigeonVar_list[3] as Double
      val brightness = pigeonVar_list[4] as Double
      val contrast = pigeonVar_list[5] as Double
      val saturation = pigeonVar_list[6] as Double
      return CamProcessingParams(blackR, blackG, blackB, gamma, brightness, contrast, saturation)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      blackR,
      blackG,
      blackB,
      gamma,
      brightness,
      contrast,
      saturation,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CamCapabilities (
  val supportedSizes: List<CamSize>,
  val isoMin: Long,
  val isoMax: Long,
  val exposureTimeMinNs: Long,
  val exposureTimeMaxNs: Long,
  val focusMin: Double,
  val focusMax: Double,
  val zoomMin: Double,
  val zoomMax: Double,
  val evCompMin: Long,
  val evCompMax: Long,
  val evCompensationStep: Double,
  /**
   * Flutter texture ID for the GPU raw stream (passthrough, no color adjustments).
   * 0 if raw stream is disabled.
   */
  val rawStreamTextureId: Long,
  /** Actual computed width of the GPU raw stream (pixels). 0 if raw stream is disabled. */
  val rawStreamWidth: Long,
  /** Requested height of the GPU raw stream (pixels). 0 if raw stream is disabled. */
  val rawStreamHeight: Long,
  /** Width of the GPU processed stream texture (pixels). Matches the largest 4:3 YUV size. */
  val streamWidth: Long,
  /** Height of the GPU processed stream texture (pixels). */
  val streamHeight: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CamCapabilities {
      val supportedSizes = pigeonVar_list[0] as List<CamSize>
      val isoMin = pigeonVar_list[1] as Long
      val isoMax = pigeonVar_list[2] as Long
      val exposureTimeMinNs = pigeonVar_list[3] as Long
      val exposureTimeMaxNs = pigeonVar_list[4] as Long
      val focusMin = pigeonVar_list[5] as Double
      val focusMax = pigeonVar_list[6] as Double
      val zoomMin = pigeonVar_list[7] as Double
      val zoomMax = pigeonVar_list[8] as Double
      val evCompMin = pigeonVar_list[9] as Long
      val evCompMax = pigeonVar_list[10] as Long
      val evCompensationStep = pigeonVar_list[11] as Double
      val rawStreamTextureId = pigeonVar_list[12] as Long
      val rawStreamWidth = pigeonVar_list[13] as Long
      val rawStreamHeight = pigeonVar_list[14] as Long
      val streamWidth = pigeonVar_list[15] as Long
      val streamHeight = pigeonVar_list[16] as Long
      return CamCapabilities(supportedSizes, isoMin, isoMax, exposureTimeMinNs, exposureTimeMaxNs, focusMin, focusMax, zoomMin, zoomMax, evCompMin, evCompMax, evCompensationStep, rawStreamTextureId, rawStreamWidth, rawStreamHeight, streamWidth, streamHeight)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      supportedSizes,
      isoMin,
      isoMax,
      exposureTimeMinNs,
      exposureTimeMaxNs,
      focusMin,
      focusMax,
      zoomMin,
      zoomMax,
      evCompMin,
      evCompMax,
      evCompensationStep,
      rawStreamTextureId,
      rawStreamWidth,
      rawStreamHeight,
      streamWidth,
      streamHeight,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CamStateUpdate (
  /** One of: "closed", "opening", "streaming", "recovering", "error" */
  val state: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CamStateUpdate {
      val state = pigeonVar_list[0] as String
      return CamStateUpdate(state)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      state,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CamError (
  val code: CamErrorCode,
  val message: String,
  val isFatal: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CamError {
      val code = pigeonVar_list[0] as CamErrorCode
      val message = pigeonVar_list[1] as String
      val isFatal = pigeonVar_list[2] as Boolean
      return CamError(code, message, isFatal)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      code,
      message,
      isFatal,
    )
  }
}

/**
 * Actual sensor values reported by the hardware after each captured frame.
 *
 * All fields are nullable — null means the hardware did not report that value.
 * Delivered via [CameraFlutterApi.onFrameResult] at ~3 Hz (every 10th frame).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CamFrameResult (
  /** Actual sensor sensitivity (ISO) used for this frame. */
  val iso: Long? = null,
  /** Actual exposure duration in nanoseconds used for this frame. */
  val exposureTimeNs: Long? = null,
  /** Actual focus distance in diopters (1/metres). 0.0 = infinity. */
  val focusDistanceDiopters: Double? = null,
  /** Red channel gain from COLOR_CORRECTION_GAINS. */
  val wbGainR: Double? = null,
  /** Green channel gain (average of greenEven + greenOdd). */
  val wbGainG: Double? = null,
  /** Blue channel gain from COLOR_CORRECTION_GAINS. */
  val wbGainB: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CamFrameResult {
      val iso = pigeonVar_list[0] as Long?
      val exposureTimeNs = pigeonVar_list[1] as Long?
      val focusDistanceDiopters = pigeonVar_list[2] as Double?
      val wbGainR = pigeonVar_list[3] as Double?
      val wbGainG = pigeonVar_list[4] as Double?
      val wbGainB = pigeonVar_list[5] as Double?
      return CamFrameResult(iso, exposureTimeNs, focusDistanceDiopters, wbGainR, wbGainG, wbGainB)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      iso,
      exposureTimeNs,
      focusDistanceDiopters,
      wbGainR,
      wbGainG,
      wbGainB,
    )
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CamErrorCode.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CamSize.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CamSettings.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CamProcessingParams.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CamCapabilities.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CamStateUpdate.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CamError.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CamFrameResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is CamErrorCode -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is CamSize -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is CamSettings -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is CamProcessingParams -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is CamCapabilities -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is CamStateUpdate -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is CamError -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is CamFrameResult -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface CameraHostApi {
  fun open(cameraId: String?, settings: CamSettings?, callback: (Result<Long>) -> Unit)
  fun getCapabilities(handle: Long, callback: (Result<CamCapabilities>) -> Unit)
  fun updateSettings(handle: Long, settings: CamSettings)
  fun setProcessingParams(handle: Long, params: CamProcessingParams)
  fun takePicture(handle: Long, callback: (Result<String>) -> Unit)
  fun getNativePipelineHandle(handle: Long, callback: (Result<Long?>) -> Unit)
  fun close(handle: Long, callback: (Result<Unit>) -> Unit)
  /**
   * Returns the current display rotation in degrees CW from portrait: 0, 90, 180, or 270.
   *
   * Used by Dart preview widgets to select the correct [RotatedBox.quarterTurns]
   * for all four device orientations, since [MediaQuery.orientation] only
   * distinguishes portrait from landscape.
   */
  fun getDisplayRotation(): Long

  companion object {
    /** The codec used by CameraHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `CameraHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: CameraHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_camera.CameraHostApi.open$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val cameraIdArg = args[0] as String?
            val settingsArg = args[1] as CamSettings?
            api.open(cameraIdArg, settingsArg) { result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_camera.CameraHostApi.getCapabilities$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            api.getCapabilities(handleArg) { result: Result<CamCapabilities> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_camera.CameraHostApi.updateSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val settingsArg = args[1] as CamSettings
            val wrapped: List<Any?> = try {
              api.updateSettings(handleArg, settingsArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_camera.CameraHostApi.setProcessingParams$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val paramsArg = args[1] as CamProcessingParams
            val wrapped: List<Any?> = try {
              api.setProcessingParams(handleArg, paramsArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_camera.CameraHostApi.takePicture$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            api.takePicture(handleArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_camera.CameraHostApi.getNativePipelineHandle$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            api.getNativePipelineHandle(handleArg) { result: Result<Long?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_camera.CameraHostApi.close$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            api.close(handleArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cambrian_camera.CameraHostApi.getDisplayRotation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getDisplayRotation())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class CameraFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by CameraFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  fun onStateChanged(handleArg: Long, stateArg: CamStateUpdate, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onStateChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(handleArg, stateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onError(handleArg: Long, errorArg: CamError, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(handleArg, errorArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onFrameResult(handleArg: Long, resultArg: CamFrameResult, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onFrameResult$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(handleArg, resultArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
