// Copyright (c) 2025 Cambrian. All rights reserved.
// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct CamSize {
  var width: Int64
  var height: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CamSize? {
    let width = pigeonVar_list[0] as! Int64
    let height = pigeonVar_list[1] as! Int64

    return CamSize(
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      width,
      height,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CamSettings {
  var iso: Int64? = nil
  var exposureTimeNs: Int64? = nil
  var focusDistanceDiopters: Double? = nil
  var zoomRatio: Double? = nil
  var afEnabled: Bool? = nil
  var awbLocked: Bool? = nil
  var noiseReductionMode: Int64? = nil
  var edgeMode: Int64? = nil
  var evCompensation: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CamSettings? {
    let iso: Int64? = nilOrValue(pigeonVar_list[0])
    let exposureTimeNs: Int64? = nilOrValue(pigeonVar_list[1])
    let focusDistanceDiopters: Double? = nilOrValue(pigeonVar_list[2])
    let zoomRatio: Double? = nilOrValue(pigeonVar_list[3])
    let afEnabled: Bool? = nilOrValue(pigeonVar_list[4])
    let awbLocked: Bool? = nilOrValue(pigeonVar_list[5])
    let noiseReductionMode: Int64? = nilOrValue(pigeonVar_list[6])
    let edgeMode: Int64? = nilOrValue(pigeonVar_list[7])
    let evCompensation: Int64? = nilOrValue(pigeonVar_list[8])

    return CamSettings(
      iso: iso,
      exposureTimeNs: exposureTimeNs,
      focusDistanceDiopters: focusDistanceDiopters,
      zoomRatio: zoomRatio,
      afEnabled: afEnabled,
      awbLocked: awbLocked,
      noiseReductionMode: noiseReductionMode,
      edgeMode: edgeMode,
      evCompensation: evCompensation
    )
  }
  func toList() -> [Any?] {
    return [
      iso,
      exposureTimeNs,
      focusDistanceDiopters,
      zoomRatio,
      afEnabled,
      awbLocked,
      noiseReductionMode,
      edgeMode,
      evCompensation,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CamProcessingParams {
  var blackR: Double
  var blackG: Double
  var blackB: Double
  var gamma: Double
  var histBlackPoint: Double
  var histWhitePoint: Double
  var autoStretch: Bool
  var autoStretchLow: Double
  var autoStretchHigh: Double
  var brightness: Double
  var saturation: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CamProcessingParams? {
    let blackR = pigeonVar_list[0] as! Double
    let blackG = pigeonVar_list[1] as! Double
    let blackB = pigeonVar_list[2] as! Double
    let gamma = pigeonVar_list[3] as! Double
    let histBlackPoint = pigeonVar_list[4] as! Double
    let histWhitePoint = pigeonVar_list[5] as! Double
    let autoStretch = pigeonVar_list[6] as! Bool
    let autoStretchLow = pigeonVar_list[7] as! Double
    let autoStretchHigh = pigeonVar_list[8] as! Double
    let brightness = pigeonVar_list[9] as! Double
    let saturation = pigeonVar_list[10] as! Double

    return CamProcessingParams(
      blackR: blackR,
      blackG: blackG,
      blackB: blackB,
      gamma: gamma,
      histBlackPoint: histBlackPoint,
      histWhitePoint: histWhitePoint,
      autoStretch: autoStretch,
      autoStretchLow: autoStretchLow,
      autoStretchHigh: autoStretchHigh,
      brightness: brightness,
      saturation: saturation
    )
  }
  func toList() -> [Any?] {
    return [
      blackR,
      blackG,
      blackB,
      gamma,
      histBlackPoint,
      histWhitePoint,
      autoStretch,
      autoStretchLow,
      autoStretchHigh,
      brightness,
      saturation,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CamCapabilities {
  var supportedSizes: [CamSize?]
  var isoMin: Int64
  var isoMax: Int64
  var exposureTimeMinNs: Int64
  var exposureTimeMaxNs: Int64
  var focusMin: Double
  var focusMax: Double
  var zoomMin: Double
  var zoomMax: Double
  var evCompMin: Int64
  var evCompMax: Int64
  var evCompensationStep: Double
  var supportsRgba8888: Bool
  var estimatedMemoryBytes: Int64
  /// Width of the YUV stream used by the C++ pipeline (pixels).
  var streamWidth: Int64
  /// Height of the YUV stream used by the C++ pipeline (pixels).
  var streamHeight: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CamCapabilities? {
    let supportedSizes = pigeonVar_list[0] as! [CamSize?]
    let isoMin = pigeonVar_list[1] as! Int64
    let isoMax = pigeonVar_list[2] as! Int64
    let exposureTimeMinNs = pigeonVar_list[3] as! Int64
    let exposureTimeMaxNs = pigeonVar_list[4] as! Int64
    let focusMin = pigeonVar_list[5] as! Double
    let focusMax = pigeonVar_list[6] as! Double
    let zoomMin = pigeonVar_list[7] as! Double
    let zoomMax = pigeonVar_list[8] as! Double
    let evCompMin = pigeonVar_list[9] as! Int64
    let evCompMax = pigeonVar_list[10] as! Int64
    let evCompensationStep = pigeonVar_list[11] as! Double
    let supportsRgba8888 = pigeonVar_list[12] as! Bool
    let estimatedMemoryBytes = pigeonVar_list[13] as! Int64
    let streamWidth = pigeonVar_list[14] as! Int64
    let streamHeight = pigeonVar_list[15] as! Int64

    return CamCapabilities(
      supportedSizes: supportedSizes,
      isoMin: isoMin,
      isoMax: isoMax,
      exposureTimeMinNs: exposureTimeMinNs,
      exposureTimeMaxNs: exposureTimeMaxNs,
      focusMin: focusMin,
      focusMax: focusMax,
      zoomMin: zoomMin,
      zoomMax: zoomMax,
      evCompMin: evCompMin,
      evCompMax: evCompMax,
      evCompensationStep: evCompensationStep,
      supportsRgba8888: supportsRgba8888,
      estimatedMemoryBytes: estimatedMemoryBytes,
      streamWidth: streamWidth,
      streamHeight: streamHeight
    )
  }
  func toList() -> [Any?] {
    return [
      supportedSizes,
      isoMin,
      isoMax,
      exposureTimeMinNs,
      exposureTimeMaxNs,
      focusMin,
      focusMax,
      zoomMin,
      zoomMax,
      evCompMin,
      evCompMax,
      evCompensationStep,
      supportsRgba8888,
      estimatedMemoryBytes,
      streamWidth,
      streamHeight,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CamStateUpdate {
  /// One of: "closed", "opening", "streaming", "recovering", "error"
  var state: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CamStateUpdate? {
    let state = pigeonVar_list[0] as! String

    return CamStateUpdate(
      state: state
    )
  }
  func toList() -> [Any?] {
    return [
      state
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CamError {
  var code: String
  var message: String
  var isFatal: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CamError? {
    let code = pigeonVar_list[0] as! String
    let message = pigeonVar_list[1] as! String
    let isFatal = pigeonVar_list[2] as! Bool

    return CamError(
      code: code,
      message: message,
      isFatal: isFatal
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      message,
      isFatal,
    ]
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return CamSize.fromList(self.readValue() as! [Any?])
    case 130:
      return CamSettings.fromList(self.readValue() as! [Any?])
    case 131:
      return CamProcessingParams.fromList(self.readValue() as! [Any?])
    case 132:
      return CamCapabilities.fromList(self.readValue() as! [Any?])
    case 133:
      return CamStateUpdate.fromList(self.readValue() as! [Any?])
    case 134:
      return CamError.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CamSize {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? CamSettings {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? CamProcessingParams {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? CamCapabilities {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? CamStateUpdate {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? CamError {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CameraHostApi {
  func open(cameraId: String?, settings: CamSettings?, completion: @escaping (Result<Int64, Error>) -> Void)
  func getCapabilities(handle: Int64, completion: @escaping (Result<CamCapabilities, Error>) -> Void)
  func updateSettings(handle: Int64, settings: CamSettings) throws
  func setProcessingParams(handle: Int64, params: CamProcessingParams) throws
  func takePicture(handle: Int64, completion: @escaping (Result<String, Error>) -> Void)
  func getNativePipelineHandle(handle: Int64, completion: @escaping (Result<Int64, Error>) -> Void)
  func close(handle: Int64, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CameraHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `CameraHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CameraHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let openChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cambrian_camera.CameraHostApi.open\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let cameraIdArg: String? = nilOrValue(args[0])
        let settingsArg: CamSettings? = nilOrValue(args[1])
        api.open(cameraId: cameraIdArg, settings: settingsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      openChannel.setMessageHandler(nil)
    }
    let getCapabilitiesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cambrian_camera.CameraHostApi.getCapabilities\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCapabilitiesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! Int64
        api.getCapabilities(handle: handleArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getCapabilitiesChannel.setMessageHandler(nil)
    }
    let updateSettingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cambrian_camera.CameraHostApi.updateSettings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateSettingsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! Int64
        let settingsArg = args[1] as! CamSettings
        do {
          try api.updateSettings(handle: handleArg, settings: settingsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateSettingsChannel.setMessageHandler(nil)
    }
    let setProcessingParamsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cambrian_camera.CameraHostApi.setProcessingParams\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setProcessingParamsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! Int64
        let paramsArg = args[1] as! CamProcessingParams
        do {
          try api.setProcessingParams(handle: handleArg, params: paramsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setProcessingParamsChannel.setMessageHandler(nil)
    }
    let takePictureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cambrian_camera.CameraHostApi.takePicture\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      takePictureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! Int64
        api.takePicture(handle: handleArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      takePictureChannel.setMessageHandler(nil)
    }
    let getNativePipelineHandleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cambrian_camera.CameraHostApi.getNativePipelineHandle\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getNativePipelineHandleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! Int64
        api.getNativePipelineHandle(handle: handleArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getNativePipelineHandleChannel.setMessageHandler(nil)
    }
    let closeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cambrian_camera.CameraHostApi.close\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! Int64
        api.close(handle: handleArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      closeChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol CameraFlutterApiProtocol {
  func onStateChanged(handle handleArg: Int64, state stateArg: CamStateUpdate, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onError(handle handleArg: Int64, error errorArg: CamError, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class CameraFlutterApi: CameraFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func onStateChanged(handle handleArg: Int64, state stateArg: CamStateUpdate, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([handleArg, stateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onError(handle handleArg: Int64, error errorArg: CamError, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([handleArg, errorArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
