// Copyright (c) 2025 Cambrian. All rights reserved.
// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Typed error codes for camera errors delivered via [CameraFlutterApi.onError].
///
/// Values are serialized as integer indices — do NOT reorder or insert in the
/// middle; only append before [unknown] to preserve wire compatibility.
enum CamErrorCode: Int {
  case cameraDevice = 0
  case cameraService = 1
  case cameraDisconnected = 2
  case configurationFailed = 3
  case permissionDenied = 4
  case cameraDisabled = 5
  case maxCamerasInUse = 6
  case cameraInUse = 7
  case cameraAccessError = 8
  case maxRetriesExceeded = 9
  case previewSurfaceLost = 10
  case pipelineError = 11
  case settingsConflict = 12
  case unknown = 13
}

/// Generated class from Pigeon that represents data sent in messages.
struct CamSize {
  var width: Int64
  var height: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CamSize? {
    let width = pigeonVar_list[0] as! Int64
    let height = pigeonVar_list[1] as! Int64

    return CamSize(
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      width,
      height,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CamSettings {
  /// "auto" | "manual" | null (don't change).
  var isoMode: String? = nil
  /// Sensor sensitivity value when isoMode == "manual".
  var iso: Int64? = nil
  /// "auto" | "manual" | null (don't change).
  var exposureMode: String? = nil
  /// Exposure duration in nanoseconds when exposureMode == "manual".
  var exposureTimeNs: Int64? = nil
  /// "auto" | "manual" | null (don't change).
  var focusMode: String? = nil
  /// Focus distance in diopters when focusMode == "manual".
  var focusDistanceDiopters: Double? = nil
  /// "auto" | "locked" | "manual" | null (don't change).
  var wbMode: String? = nil
  /// Red gain multiplier when wbMode == "manual".
  var wbGainR: Double? = nil
  /// Green gain multiplier when wbMode == "manual".
  var wbGainG: Double? = nil
  /// Blue gain multiplier when wbMode == "manual".
  var wbGainB: Double? = nil
  /// Zoom ratio (1.0 = no zoom). Null = don't change.
  var zoomRatio: Double? = nil
  /// Camera2 NOISE_REDUCTION_MODE_* constant. Null = don't change.
  var noiseReductionMode: Int64? = nil
  /// Camera2 EDGE_MODE_* constant. Null = don't change.
  var edgeMode: Int64? = nil
  /// Exposure compensation in AE steps. Null = don't change.
  /// NOTE: has no effect when isoMode == "manual" or exposureMode == "manual"
  /// because CONTROL_AE_MODE is set to OFF in that case.
  var evCompensation: Int64? = nil
  /// Enable GPU raw (passthrough) stream. Null = don't change.
  var enableRawStream: Bool? = nil
  /// Requested height of the GPU raw stream in pixels. Null = don't change. 0 = use default.
  var rawStreamHeight: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CamSettings? {
    let isoMode: String? = nilOrValue(pigeonVar_list[0])
    let iso: Int64? = nilOrValue(pigeonVar_list[1])
    let exposureMode: String? = nilOrValue(pigeonVar_list[2])
    let exposureTimeNs: Int64? = nilOrValue(pigeonVar_list[3])
    let focusMode: String? = nilOrValue(pigeonVar_list[4])
    let focusDistanceDiopters: Double? = nilOrValue(pigeonVar_list[5])
    let wbMode: String? = nilOrValue(pigeonVar_list[6])
    let wbGainR: Double? = nilOrValue(pigeonVar_list[7])
    let wbGainG: Double? = nilOrValue(pigeonVar_list[8])
    let wbGainB: Double? = nilOrValue(pigeonVar_list[9])
    let zoomRatio: Double? = nilOrValue(pigeonVar_list[10])
    let noiseReductionMode: Int64? = nilOrValue(pigeonVar_list[11])
    let edgeMode: Int64? = nilOrValue(pigeonVar_list[12])
    let evCompensation: Int64? = nilOrValue(pigeonVar_list[13])
    let enableRawStream: Bool? = nilOrValue(pigeonVar_list[14])
    let rawStreamHeight: Int64? = nilOrValue(pigeonVar_list[15])

    return CamSettings(
      isoMode: isoMode,
      iso: iso,
      exposureMode: exposureMode,
      exposureTimeNs: exposureTimeNs,
      focusMode: focusMode,
      focusDistanceDiopters: focusDistanceDiopters,
      wbMode: wbMode,
      wbGainR: wbGainR,
      wbGainG: wbGainG,
      wbGainB: wbGainB,
      zoomRatio: zoomRatio,
      noiseReductionMode: noiseReductionMode,
      edgeMode: edgeMode,
      evCompensation: evCompensation,
      enableRawStream: enableRawStream,
      rawStreamHeight: rawStreamHeight
    )
  }
  func toList() -> [Any?] {
    return [
      isoMode,
      iso,
      exposureMode,
      exposureTimeNs,
      focusMode,
      focusDistanceDiopters,
      wbMode,
      wbGainR,
      wbGainG,
      wbGainB,
      zoomRatio,
      noiseReductionMode,
      edgeMode,
      evCompensation,
      enableRawStream,
      rawStreamHeight,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CamProcessingParams {
  var blackR: Double
  var blackG: Double
  var blackB: Double
  var gamma: Double
  var brightness: Double
  var contrast: Double
  var saturation: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CamProcessingParams? {
    let blackR = pigeonVar_list[0] as! Double
    let blackG = pigeonVar_list[1] as! Double
    let blackB = pigeonVar_list[2] as! Double
    let gamma = pigeonVar_list[3] as! Double
    let brightness = pigeonVar_list[4] as! Double
    let contrast = pigeonVar_list[5] as! Double
    let saturation = pigeonVar_list[6] as! Double

    return CamProcessingParams(
      blackR: blackR,
      blackG: blackG,
      blackB: blackB,
      gamma: gamma,
      brightness: brightness,
      contrast: contrast,
      saturation: saturation
    )
  }
  func toList() -> [Any?] {
    return [
      blackR,
      blackG,
      blackB,
      gamma,
      brightness,
      contrast,
      saturation,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CamCapabilities {
  var supportedSizes: [CamSize]
  var isoMin: Int64
  var isoMax: Int64
  var exposureTimeMinNs: Int64
  var exposureTimeMaxNs: Int64
  var focusMin: Double
  var focusMax: Double
  var zoomMin: Double
  var zoomMax: Double
  var evCompMin: Int64
  var evCompMax: Int64
  var evCompensationStep: Double
  /// Flutter texture ID for the GPU raw stream (passthrough, no color adjustments).
  /// 0 if raw stream is disabled.
  var rawStreamTextureId: Int64
  /// Actual computed width of the GPU raw stream (pixels). 0 if raw stream is disabled.
  var rawStreamWidth: Int64
  /// Requested height of the GPU raw stream (pixels). 0 if raw stream is disabled.
  var rawStreamHeight: Int64
  /// Width of the GPU processed stream texture (pixels). Matches the largest 4:3 YUV size.
  var streamWidth: Int64
  /// Height of the GPU processed stream texture (pixels).
  var streamHeight: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CamCapabilities? {
    let supportedSizes = pigeonVar_list[0] as! [CamSize]
    let isoMin = pigeonVar_list[1] as! Int64
    let isoMax = pigeonVar_list[2] as! Int64
    let exposureTimeMinNs = pigeonVar_list[3] as! Int64
    let exposureTimeMaxNs = pigeonVar_list[4] as! Int64
    let focusMin = pigeonVar_list[5] as! Double
    let focusMax = pigeonVar_list[6] as! Double
    let zoomMin = pigeonVar_list[7] as! Double
    let zoomMax = pigeonVar_list[8] as! Double
    let evCompMin = pigeonVar_list[9] as! Int64
    let evCompMax = pigeonVar_list[10] as! Int64
    let evCompensationStep = pigeonVar_list[11] as! Double
    let rawStreamTextureId = pigeonVar_list[12] as! Int64
    let rawStreamWidth = pigeonVar_list[13] as! Int64
    let rawStreamHeight = pigeonVar_list[14] as! Int64
    let streamWidth = pigeonVar_list[15] as! Int64
    let streamHeight = pigeonVar_list[16] as! Int64

    return CamCapabilities(
      supportedSizes: supportedSizes,
      isoMin: isoMin,
      isoMax: isoMax,
      exposureTimeMinNs: exposureTimeMinNs,
      exposureTimeMaxNs: exposureTimeMaxNs,
      focusMin: focusMin,
      focusMax: focusMax,
      zoomMin: zoomMin,
      zoomMax: zoomMax,
      evCompMin: evCompMin,
      evCompMax: evCompMax,
      evCompensationStep: evCompensationStep,
      rawStreamTextureId: rawStreamTextureId,
      rawStreamWidth: rawStreamWidth,
      rawStreamHeight: rawStreamHeight,
      streamWidth: streamWidth,
      streamHeight: streamHeight
    )
  }
  func toList() -> [Any?] {
    return [
      supportedSizes,
      isoMin,
      isoMax,
      exposureTimeMinNs,
      exposureTimeMaxNs,
      focusMin,
      focusMax,
      zoomMin,
      zoomMax,
      evCompMin,
      evCompMax,
      evCompensationStep,
      rawStreamTextureId,
      rawStreamWidth,
      rawStreamHeight,
      streamWidth,
      streamHeight,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CamStateUpdate {
  /// One of: "closed", "opening", "streaming", "recovering", "error"
  var state: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CamStateUpdate? {
    let state = pigeonVar_list[0] as! String

    return CamStateUpdate(
      state: state
    )
  }
  func toList() -> [Any?] {
    return [
      state
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CamError {
  var code: CamErrorCode
  var message: String
  var isFatal: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CamError? {
    let code = pigeonVar_list[0] as! CamErrorCode
    let message = pigeonVar_list[1] as! String
    let isFatal = pigeonVar_list[2] as! Bool

    return CamError(
      code: code,
      message: message,
      isFatal: isFatal
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      message,
      isFatal,
    ]
  }
}

/// Actual sensor values reported by the hardware after each captured frame.
///
/// All fields are nullable — null means the hardware did not report that value.
/// Delivered via [CameraFlutterApi.onFrameResult] at ~3 Hz (every 10th frame).
///
/// Generated class from Pigeon that represents data sent in messages.
struct CamFrameResult {
  /// Actual sensor sensitivity (ISO) used for this frame.
  var iso: Int64? = nil
  /// Actual exposure duration in nanoseconds used for this frame.
  var exposureTimeNs: Int64? = nil
  /// Actual focus distance in diopters (1/metres). 0.0 = infinity.
  var focusDistanceDiopters: Double? = nil
  /// Red channel gain from COLOR_CORRECTION_GAINS.
  var wbGainR: Double? = nil
  /// Green channel gain (average of greenEven + greenOdd).
  var wbGainG: Double? = nil
  /// Blue channel gain from COLOR_CORRECTION_GAINS.
  var wbGainB: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CamFrameResult? {
    let iso: Int64? = nilOrValue(pigeonVar_list[0])
    let exposureTimeNs: Int64? = nilOrValue(pigeonVar_list[1])
    let focusDistanceDiopters: Double? = nilOrValue(pigeonVar_list[2])
    let wbGainR: Double? = nilOrValue(pigeonVar_list[3])
    let wbGainG: Double? = nilOrValue(pigeonVar_list[4])
    let wbGainB: Double? = nilOrValue(pigeonVar_list[5])

    return CamFrameResult(
      iso: iso,
      exposureTimeNs: exposureTimeNs,
      focusDistanceDiopters: focusDistanceDiopters,
      wbGainR: wbGainR,
      wbGainG: wbGainG,
      wbGainB: wbGainB
    )
  }
  func toList() -> [Any?] {
    return [
      iso,
      exposureTimeNs,
      focusDistanceDiopters,
      wbGainR,
      wbGainG,
      wbGainB,
    ]
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CamErrorCode(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return CamSize.fromList(self.readValue() as! [Any?])
    case 131:
      return CamSettings.fromList(self.readValue() as! [Any?])
    case 132:
      return CamProcessingParams.fromList(self.readValue() as! [Any?])
    case 133:
      return CamCapabilities.fromList(self.readValue() as! [Any?])
    case 134:
      return CamStateUpdate.fromList(self.readValue() as! [Any?])
    case 135:
      return CamError.fromList(self.readValue() as! [Any?])
    case 136:
      return CamFrameResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CamErrorCode {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? CamSize {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? CamSettings {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? CamProcessingParams {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? CamCapabilities {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? CamStateUpdate {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? CamError {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? CamFrameResult {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CameraHostApi {
  func open(cameraId: String?, settings: CamSettings?, completion: @escaping (Result<Int64, Error>) -> Void)
  func getCapabilities(handle: Int64, completion: @escaping (Result<CamCapabilities, Error>) -> Void)
  func updateSettings(handle: Int64, settings: CamSettings) throws
  func setProcessingParams(handle: Int64, params: CamProcessingParams) throws
  func takePicture(handle: Int64, completion: @escaping (Result<String, Error>) -> Void)
  func getNativePipelineHandle(handle: Int64, completion: @escaping (Result<Int64?, Error>) -> Void)
  func startRecording(handle: Int64, completion: @escaping (Result<String, Error>) -> Void)
  func stopRecording(handle: Int64, completion: @escaping (Result<String, Error>) -> Void)
  func close(handle: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  /// Returns the current display rotation in degrees CW from portrait: 0, 90, 180, or 270.
  ///
  /// Used by Dart preview widgets to select the correct [RotatedBox.quarterTurns]
  /// for all four device orientations, since [MediaQuery.orientation] only
  /// distinguishes portrait from landscape.
  func getDisplayRotation() throws -> Int64
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CameraHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `CameraHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CameraHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let openChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cambrian_camera.CameraHostApi.open\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let cameraIdArg: String? = nilOrValue(args[0])
        let settingsArg: CamSettings? = nilOrValue(args[1])
        api.open(cameraId: cameraIdArg, settings: settingsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      openChannel.setMessageHandler(nil)
    }
    let getCapabilitiesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cambrian_camera.CameraHostApi.getCapabilities\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCapabilitiesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! Int64
        api.getCapabilities(handle: handleArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getCapabilitiesChannel.setMessageHandler(nil)
    }
    let updateSettingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cambrian_camera.CameraHostApi.updateSettings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateSettingsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! Int64
        let settingsArg = args[1] as! CamSettings
        do {
          try api.updateSettings(handle: handleArg, settings: settingsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateSettingsChannel.setMessageHandler(nil)
    }
    let setProcessingParamsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cambrian_camera.CameraHostApi.setProcessingParams\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setProcessingParamsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! Int64
        let paramsArg = args[1] as! CamProcessingParams
        do {
          try api.setProcessingParams(handle: handleArg, params: paramsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setProcessingParamsChannel.setMessageHandler(nil)
    }
    let takePictureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cambrian_camera.CameraHostApi.takePicture\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      takePictureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! Int64
        api.takePicture(handle: handleArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      takePictureChannel.setMessageHandler(nil)
    }
    let getNativePipelineHandleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cambrian_camera.CameraHostApi.getNativePipelineHandle\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getNativePipelineHandleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! Int64
        api.getNativePipelineHandle(handle: handleArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getNativePipelineHandleChannel.setMessageHandler(nil)
    }
    let startRecordingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cambrian_camera.CameraHostApi.startRecording\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startRecordingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! Int64
        api.startRecording(handle: handleArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startRecordingChannel.setMessageHandler(nil)
    }
    let stopRecordingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cambrian_camera.CameraHostApi.stopRecording\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopRecordingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! Int64
        api.stopRecording(handle: handleArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopRecordingChannel.setMessageHandler(nil)
    }
    let closeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cambrian_camera.CameraHostApi.close\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! Int64
        api.close(handle: handleArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      closeChannel.setMessageHandler(nil)
    }
    /// Returns the current display rotation in degrees CW from portrait: 0, 90, 180, or 270.
    ///
    /// Used by Dart preview widgets to select the correct [RotatedBox.quarterTurns]
    /// for all four device orientations, since [MediaQuery.orientation] only
    /// distinguishes portrait from landscape.
    let getDisplayRotationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cambrian_camera.CameraHostApi.getDisplayRotation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDisplayRotationChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getDisplayRotation()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getDisplayRotationChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol CameraFlutterApiProtocol {
  func onStateChanged(handle handleArg: Int64, state stateArg: CamStateUpdate, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onError(handle handleArg: Int64, error errorArg: CamError, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onFrameResult(handle handleArg: Int64, result resultArg: CamFrameResult, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Called when the recording state changes.
  /// [state] is one of: "recording", "idle", "error".
  func onRecordingStateChanged(handle handleArg: Int64, state stateArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class CameraFlutterApi: CameraFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func onStateChanged(handle handleArg: Int64, state stateArg: CamStateUpdate, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([handleArg, stateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: Any? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onError(handle handleArg: Int64, error errorArg: CamError, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([handleArg, errorArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: Any? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onFrameResult(handle handleArg: Int64, result resultArg: CamFrameResult, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onFrameResult\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([handleArg, resultArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: Any? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// Called when the recording state changes.
  /// [state] is one of: "recording", "idle", "error".
  func onRecordingStateChanged(handle handleArg: Int64, state stateArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onRecordingStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([handleArg, stateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: Any? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
