// Copyright (c) 2025 Cambrian. All rights reserved.
// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

/// Typed error codes for camera errors delivered via [CameraFlutterApi.onError].
///
/// Values are serialized as integer indices — do NOT reorder or insert in the
/// middle; only append before [unknown] to preserve wire compatibility.
enum CamErrorCode {
  cameraDevice,
  cameraService,
  cameraDisconnected,
  configurationFailed,
  permissionDenied,
  cameraDisabled,
  maxCamerasInUse,
  cameraInUse,
  cameraAccessError,
  maxRetriesExceeded,
  previewSurfaceLost,
  pipelineError,
  settingsConflict,
  unknown,
}

class CamSize {
  CamSize({
    required this.width,
    required this.height,
  });

  int width;

  int height;

  Object encode() {
    return <Object?>[
      width,
      height,
    ];
  }

  static CamSize decode(Object result) {
    result as List<Object?>;
    return CamSize(
      width: result[0]! as int,
      height: result[1]! as int,
    );
  }
}

class CamSettings {
  CamSettings({
    this.isoMode,
    this.iso,
    this.exposureMode,
    this.exposureTimeNs,
    this.focusMode,
    this.focusDistanceDiopters,
    this.wbMode,
    this.wbGainR,
    this.wbGainG,
    this.wbGainB,
    this.zoomRatio,
    this.noiseReductionMode,
    this.edgeMode,
    this.evCompensation,
    this.enableRawStream,
    this.rawStreamHeight,
  });

  /// "auto" | "manual" | null (don't change).
  String? isoMode;

  /// Sensor sensitivity value when isoMode == "manual".
  int? iso;

  /// "auto" | "manual" | null (don't change).
  String? exposureMode;

  /// Exposure duration in nanoseconds when exposureMode == "manual".
  int? exposureTimeNs;

  /// "auto" | "manual" | null (don't change).
  String? focusMode;

  /// Focus distance in diopters when focusMode == "manual".
  double? focusDistanceDiopters;

  /// "auto" | "locked" | "manual" | null (don't change).
  String? wbMode;

  /// Red gain multiplier when wbMode == "manual".
  double? wbGainR;

  /// Green gain multiplier when wbMode == "manual".
  double? wbGainG;

  /// Blue gain multiplier when wbMode == "manual".
  double? wbGainB;

  /// Zoom ratio (1.0 = no zoom). Null = don't change.
  double? zoomRatio;

  /// Camera2 NOISE_REDUCTION_MODE_* constant. Null = don't change.
  int? noiseReductionMode;

  /// Camera2 EDGE_MODE_* constant. Null = don't change.
  int? edgeMode;

  /// Exposure compensation in AE steps. Null = don't change.
  /// NOTE: has no effect when isoMode == "manual" or exposureMode == "manual"
  /// because CONTROL_AE_MODE is set to OFF in that case.
  int? evCompensation;

  /// Enable GPU raw (passthrough) stream. Null = don't change.
  bool? enableRawStream;

  /// Requested height of the GPU raw stream in pixels. Null = don't change. 0 = use default.
  int? rawStreamHeight;

  Object encode() {
    return <Object?>[
      isoMode,
      iso,
      exposureMode,
      exposureTimeNs,
      focusMode,
      focusDistanceDiopters,
      wbMode,
      wbGainR,
      wbGainG,
      wbGainB,
      zoomRatio,
      noiseReductionMode,
      edgeMode,
      evCompensation,
      enableRawStream,
      rawStreamHeight,
    ];
  }

  static CamSettings decode(Object result) {
    result as List<Object?>;
    return CamSettings(
      isoMode: result[0] as String?,
      iso: result[1] as int?,
      exposureMode: result[2] as String?,
      exposureTimeNs: result[3] as int?,
      focusMode: result[4] as String?,
      focusDistanceDiopters: result[5] as double?,
      wbMode: result[6] as String?,
      wbGainR: result[7] as double?,
      wbGainG: result[8] as double?,
      wbGainB: result[9] as double?,
      zoomRatio: result[10] as double?,
      noiseReductionMode: result[11] as int?,
      edgeMode: result[12] as int?,
      evCompensation: result[13] as int?,
      enableRawStream: result[14] as bool?,
      rawStreamHeight: result[15] as int?,
    );
  }
}

class CamProcessingParams {
  CamProcessingParams({
    required this.blackR,
    required this.blackG,
    required this.blackB,
    required this.gamma,
    required this.brightness,
    required this.contrast,
    required this.saturation,
  });

  double blackR;

  double blackG;

  double blackB;

  double gamma;

  double brightness;

  double contrast;

  double saturation;

  Object encode() {
    return <Object?>[
      blackR,
      blackG,
      blackB,
      gamma,
      brightness,
      contrast,
      saturation,
    ];
  }

  static CamProcessingParams decode(Object result) {
    result as List<Object?>;
    return CamProcessingParams(
      blackR: result[0]! as double,
      blackG: result[1]! as double,
      blackB: result[2]! as double,
      gamma: result[3]! as double,
      brightness: result[4]! as double,
      contrast: result[5]! as double,
      saturation: result[6]! as double,
    );
  }
}

class CamCapabilities {
  CamCapabilities({
    required this.supportedSizes,
    required this.isoMin,
    required this.isoMax,
    required this.exposureTimeMinNs,
    required this.exposureTimeMaxNs,
    required this.focusMin,
    required this.focusMax,
    required this.zoomMin,
    required this.zoomMax,
    required this.evCompMin,
    required this.evCompMax,
    required this.evCompensationStep,
    required this.rawStreamTextureId,
    required this.rawStreamWidth,
    required this.rawStreamHeight,
    required this.streamWidth,
    required this.streamHeight,
  });

  List<CamSize> supportedSizes;

  int isoMin;

  int isoMax;

  int exposureTimeMinNs;

  int exposureTimeMaxNs;

  double focusMin;

  double focusMax;

  double zoomMin;

  double zoomMax;

  int evCompMin;

  int evCompMax;

  double evCompensationStep;

  /// Flutter texture ID for the GPU raw stream (passthrough, no color adjustments).
  /// 0 if raw stream is disabled.
  int rawStreamTextureId;

  /// Actual computed width of the GPU raw stream (pixels). 0 if raw stream is disabled.
  int rawStreamWidth;

  /// Requested height of the GPU raw stream (pixels). 0 if raw stream is disabled.
  int rawStreamHeight;

  /// Width of the GPU processed stream texture (pixels). Matches the largest 4:3 YUV size.
  int streamWidth;

  /// Height of the GPU processed stream texture (pixels).
  int streamHeight;

  Object encode() {
    return <Object?>[
      supportedSizes,
      isoMin,
      isoMax,
      exposureTimeMinNs,
      exposureTimeMaxNs,
      focusMin,
      focusMax,
      zoomMin,
      zoomMax,
      evCompMin,
      evCompMax,
      evCompensationStep,
      rawStreamTextureId,
      rawStreamWidth,
      rawStreamHeight,
      streamWidth,
      streamHeight,
    ];
  }

  static CamCapabilities decode(Object result) {
    result as List<Object?>;
    return CamCapabilities(
      supportedSizes: (result[0] as List<Object?>?)!.cast<CamSize>(),
      isoMin: result[1]! as int,
      isoMax: result[2]! as int,
      exposureTimeMinNs: result[3]! as int,
      exposureTimeMaxNs: result[4]! as int,
      focusMin: result[5]! as double,
      focusMax: result[6]! as double,
      zoomMin: result[7]! as double,
      zoomMax: result[8]! as double,
      evCompMin: result[9]! as int,
      evCompMax: result[10]! as int,
      evCompensationStep: result[11]! as double,
      rawStreamTextureId: result[12]! as int,
      rawStreamWidth: result[13]! as int,
      rawStreamHeight: result[14]! as int,
      streamWidth: result[15]! as int,
      streamHeight: result[16]! as int,
    );
  }
}

class CamStateUpdate {
  CamStateUpdate({
    required this.state,
  });

  /// One of: "closed", "opening", "streaming", "recovering", "error"
  String state;

  Object encode() {
    return <Object?>[
      state,
    ];
  }

  static CamStateUpdate decode(Object result) {
    result as List<Object?>;
    return CamStateUpdate(
      state: result[0]! as String,
    );
  }
}

class CamError {
  CamError({
    required this.code,
    required this.message,
    required this.isFatal,
  });

  CamErrorCode code;

  String message;

  bool isFatal;

  Object encode() {
    return <Object?>[
      code,
      message,
      isFatal,
    ];
  }

  static CamError decode(Object result) {
    result as List<Object?>;
    return CamError(
      code: result[0]! as CamErrorCode,
      message: result[1]! as String,
      isFatal: result[2]! as bool,
    );
  }
}

/// Actual sensor values reported by the hardware after each captured frame.
///
/// All fields are nullable — null means the hardware did not report that value.
/// Delivered via [CameraFlutterApi.onFrameResult] at ~3 Hz (every 10th frame).
class CamFrameResult {
  CamFrameResult({
    this.iso,
    this.exposureTimeNs,
    this.focusDistanceDiopters,
    this.wbGainR,
    this.wbGainG,
    this.wbGainB,
  });

  /// Actual sensor sensitivity (ISO) used for this frame.
  int? iso;

  /// Actual exposure duration in nanoseconds used for this frame.
  int? exposureTimeNs;

  /// Actual focus distance in diopters (1/metres). 0.0 = infinity.
  double? focusDistanceDiopters;

  /// Red channel gain from COLOR_CORRECTION_GAINS.
  double? wbGainR;

  /// Green channel gain (average of greenEven + greenOdd).
  double? wbGainG;

  /// Blue channel gain from COLOR_CORRECTION_GAINS.
  double? wbGainB;

  Object encode() {
    return <Object?>[
      iso,
      exposureTimeNs,
      focusDistanceDiopters,
      wbGainR,
      wbGainG,
      wbGainB,
    ];
  }

  static CamFrameResult decode(Object result) {
    result as List<Object?>;
    return CamFrameResult(
      iso: result[0] as int?,
      exposureTimeNs: result[1] as int?,
      focusDistanceDiopters: result[2] as double?,
      wbGainR: result[3] as double?,
      wbGainG: result[4] as double?,
      wbGainB: result[5] as double?,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is CamErrorCode) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is CamSize) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is CamSettings) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is CamProcessingParams) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is CamCapabilities) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is CamStateUpdate) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is CamError) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is CamFrameResult) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : CamErrorCode.values[value];
      case 130: 
        return CamSize.decode(readValue(buffer)!);
      case 131: 
        return CamSettings.decode(readValue(buffer)!);
      case 132: 
        return CamProcessingParams.decode(readValue(buffer)!);
      case 133: 
        return CamCapabilities.decode(readValue(buffer)!);
      case 134: 
        return CamStateUpdate.decode(readValue(buffer)!);
      case 135: 
        return CamError.decode(readValue(buffer)!);
      case 136: 
        return CamFrameResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class CameraHostApi {
  /// Constructor for [CameraHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  CameraHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<int> open(String? cameraId, CamSettings? settings) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_camera.CameraHostApi.open$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[cameraId, settings]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as int?)!;
    }
  }

  Future<CamCapabilities> getCapabilities(int handle) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_camera.CameraHostApi.getCapabilities$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[handle]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as CamCapabilities?)!;
    }
  }

  Future<void> updateSettings(int handle, CamSettings settings) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_camera.CameraHostApi.updateSettings$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[handle, settings]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setProcessingParams(int handle, CamProcessingParams params) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_camera.CameraHostApi.setProcessingParams$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[handle, params]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<String> takePicture(int handle) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_camera.CameraHostApi.takePicture$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[handle]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<int?> getNativePipelineHandle(int handle) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_camera.CameraHostApi.getNativePipelineHandle$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[handle]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as int?);
    }
  }

  Future<String> startRecording(int handle, String? outputDirectory, String? fileName) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_camera.CameraHostApi.startRecording$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[handle, outputDirectory, fileName]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<String> stopRecording(int handle) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_camera.CameraHostApi.stopRecording$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[handle]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<void> close(int handle) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_camera.CameraHostApi.close$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[handle]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Returns the current display rotation in degrees CW from portrait: 0, 90, 180, or 270.
  ///
  /// Used by Dart preview widgets to select the correct [RotatedBox.quarterTurns]
  /// for all four device orientations, since [MediaQuery.orientation] only
  /// distinguishes portrait from landscape.
  Future<int> getDisplayRotation() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_camera.CameraHostApi.getDisplayRotation$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as int?)!;
    }
  }
}

abstract class CameraFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onStateChanged(int handle, CamStateUpdate state);

  void onError(int handle, CamError error);

  void onFrameResult(int handle, CamFrameResult result);

  /// Called when the recording state changes.
  /// [state] is one of: "recording", "idle", "error".
  void onRecordingStateChanged(int handle, String state);

  static void setUp(CameraFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onStateChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onStateChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_handle = (args[0] as int?);
          assert(arg_handle != null,
              'Argument for dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onStateChanged was null, expected non-null int.');
          final CamStateUpdate? arg_state = (args[1] as CamStateUpdate?);
          assert(arg_state != null,
              'Argument for dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onStateChanged was null, expected non-null CamStateUpdate.');
          try {
            api.onStateChanged(arg_handle!, arg_state!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onError$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onError was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_handle = (args[0] as int?);
          assert(arg_handle != null,
              'Argument for dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onError was null, expected non-null int.');
          final CamError? arg_error = (args[1] as CamError?);
          assert(arg_error != null,
              'Argument for dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onError was null, expected non-null CamError.');
          try {
            api.onError(arg_handle!, arg_error!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onFrameResult$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onFrameResult was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_handle = (args[0] as int?);
          assert(arg_handle != null,
              'Argument for dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onFrameResult was null, expected non-null int.');
          final CamFrameResult? arg_result = (args[1] as CamFrameResult?);
          assert(arg_result != null,
              'Argument for dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onFrameResult was null, expected non-null CamFrameResult.');
          try {
            api.onFrameResult(arg_handle!, arg_result!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onRecordingStateChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onRecordingStateChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_handle = (args[0] as int?);
          assert(arg_handle != null,
              'Argument for dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onRecordingStateChanged was null, expected non-null int.');
          final String? arg_state = (args[1] as String?);
          assert(arg_state != null,
              'Argument for dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onRecordingStateChanged was null, expected non-null String.');
          try {
            api.onRecordingStateChanged(arg_handle!, arg_state!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
