// Copyright (c) 2025 Cambrian. All rights reserved.
// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

/// Typed error codes for camera errors delivered via [CameraFlutterApi.onError].
///
/// Values are serialized as integer indices — do NOT reorder or insert in the
/// middle; only append before [unknown] to preserve wire compatibility.
enum CamErrorCode {
  cameraDevice,
  cameraService,
  cameraDisconnected,
  configurationFailed,
  permissionDenied,
  cameraDisabled,
  maxCamerasInUse,
  cameraInUse,
  cameraAccessError,
  maxRetriesExceeded,
  previewSurfaceLost,
  pipelineError,
  settingsConflict,
  frameStall,
  captureFailure,
  fpsDegraded,
  aeConvergenceTimeout,
  recordingTruncated,
  unknown,
}

class CamSize {
  CamSize({
    required this.width,
    required this.height,
  });

  int width;

  int height;

  Object encode() {
    return <Object?>[
      width,
      height,
    ];
  }

  static CamSize decode(Object result) {
    result as List<Object?>;
    return CamSize(
      width: result[0]! as int,
      height: result[1]! as int,
    );
  }
}

class CamSettings {
  CamSettings({
    this.isoMode,
    this.iso,
    this.exposureMode,
    this.exposureTimeNs,
    this.focusMode,
    this.focusDistanceDiopters,
    this.wbMode,
    this.wbGainR,
    this.wbGainG,
    this.wbGainB,
    this.zoomRatio,
    this.noiseReductionMode,
    this.edgeMode,
    this.evCompensation,
    this.enableNaturalStream,
    this.naturalStreamHeight,
    this.cropOutputSize,
  });

  /// "auto" | "manual" | null (don't change).
  String? isoMode;

  /// Sensor sensitivity value when isoMode == "manual".
  int? iso;

  /// "auto" | "manual" | null (don't change).
  String? exposureMode;

  /// Exposure duration in nanoseconds when exposureMode == "manual".
  int? exposureTimeNs;

  /// "auto" | "manual" | null (don't change).
  String? focusMode;

  /// Focus distance in diopters when focusMode == "manual".
  double? focusDistanceDiopters;

  /// "auto" | "locked" | "manual" | null (don't change).
  String? wbMode;

  /// Red gain multiplier when wbMode == "manual".
  double? wbGainR;

  /// Green gain multiplier when wbMode == "manual".
  double? wbGainG;

  /// Blue gain multiplier when wbMode == "manual".
  double? wbGainB;

  /// Zoom ratio (1.0 = no zoom). Null = don't change.
  double? zoomRatio;

  /// Camera2 NOISE_REDUCTION_MODE_* constant. Null = don't change.
  int? noiseReductionMode;

  /// Camera2 EDGE_MODE_* constant. Null = don't change.
  int? edgeMode;

  /// Exposure compensation in AE steps. Null = don't change.
  /// NOTE: has no effect when isoMode == "manual" or exposureMode == "manual"
  /// because CONTROL_AE_MODE is set to OFF in that case.
  int? evCompensation;

  /// Enable GPU natural (unprocessed/passthrough) stream. Null = don't change.
  bool? enableNaturalStream;

  /// Requested height of the GPU natural stream in pixels. Null = don't change. 0 = use default.
  int? naturalStreamHeight;

  /// Center-crop the GPU output to this exact pixel size.
  ///
  /// When set, the GPU fragment shader samples from the centered
  /// sub-rectangle of the configured stream, and the output FBO/PBO/preview
  /// buffers are resized to these dims. All downstream consumers — preview
  /// surface, raw stream, 480p C++ sink, `captureImage()`, video recording —
  /// receive frames at the cropped dims. The camera session stays at full
  /// sensor resolution (no Camera2 reconfigure, no `SCALER_CROP_REGION`).
  ///
  /// Null = "don't change the current crop" (matches the latest-value-wins
  /// semantics of the other CamSettings fields). To CLEAR an active crop,
  /// send `cropOutputSize` equal to the current sensor stream dims. The
  /// Kotlin side detects that output == source and removes the crop,
  /// restoring full-sensor output without a Camera2 session restart.
  /// The initial state before any crop has been set is "no crop".
  ///
  /// Constraints (enforced on the Kotlin side; caller receives
  /// `FlutterError("invalid_crop", ...)` on violation):
  ///   - `0 < width  <= streamWidth`
  ///   - `0 < height <= streamHeight`
  ///   - `width  % 2 == 0` (GPU/PBO/encoder alignment)
  ///   - `height % 2 == 0`
  ///
  /// Aspect ratio is NOT constrained: cropping a 4160×3120 stream to
  /// 1920×1080 is a valid request and produces a symmetric
  /// letterbox-style center crop.
  ///
  /// **Interaction with `zoomRatio`:** zoom and crop compose
  /// multiplicatively. The ISP delivers a zoomed full-resolution frame to
  /// the GPU, which then center-crops it. Effective zoom from the caller's
  /// perspective is approximately `zoomRatio × (streamWidth / cropWidth)`.
  ///
  /// **Interaction with `captureNaturalPicture()`:** that method
  /// intentionally ignores `cropOutputSize` and always returns the
  /// full-sensor hardware JPEG. Use `captureImage()` if you want the
  /// cropped image.
  CamSize? cropOutputSize;

  Object encode() {
    return <Object?>[
      isoMode,
      iso,
      exposureMode,
      exposureTimeNs,
      focusMode,
      focusDistanceDiopters,
      wbMode,
      wbGainR,
      wbGainG,
      wbGainB,
      zoomRatio,
      noiseReductionMode,
      edgeMode,
      evCompensation,
      enableNaturalStream,
      naturalStreamHeight,
      cropOutputSize,
    ];
  }

  static CamSettings decode(Object result) {
    result as List<Object?>;
    return CamSettings(
      isoMode: result[0] as String?,
      iso: result[1] as int?,
      exposureMode: result[2] as String?,
      exposureTimeNs: result[3] as int?,
      focusMode: result[4] as String?,
      focusDistanceDiopters: result[5] as double?,
      wbMode: result[6] as String?,
      wbGainR: result[7] as double?,
      wbGainG: result[8] as double?,
      wbGainB: result[9] as double?,
      zoomRatio: result[10] as double?,
      noiseReductionMode: result[11] as int?,
      edgeMode: result[12] as int?,
      evCompensation: result[13] as int?,
      enableNaturalStream: result[14] as bool?,
      naturalStreamHeight: result[15] as int?,
      cropOutputSize: result[16] as CamSize?,
    );
  }
}

class CamProcessingParams {
  CamProcessingParams({
    required this.blackR,
    required this.blackG,
    required this.blackB,
    required this.gamma,
    required this.brightness,
    required this.contrast,
    required this.saturation,
  });

  double blackR;

  double blackG;

  double blackB;

  double gamma;

  double brightness;

  double contrast;

  double saturation;

  Object encode() {
    return <Object?>[
      blackR,
      blackG,
      blackB,
      gamma,
      brightness,
      contrast,
      saturation,
    ];
  }

  static CamProcessingParams decode(Object result) {
    result as List<Object?>;
    return CamProcessingParams(
      blackR: result[0]! as double,
      blackG: result[1]! as double,
      blackB: result[2]! as double,
      gamma: result[3]! as double,
      brightness: result[4]! as double,
      contrast: result[5]! as double,
      saturation: result[6]! as double,
    );
  }
}

class CamCapabilities {
  CamCapabilities({
    required this.supportedSizes,
    required this.isoMin,
    required this.isoMax,
    required this.exposureTimeMinNs,
    required this.exposureTimeMaxNs,
    required this.focusMin,
    required this.focusMax,
    required this.zoomMin,
    required this.zoomMax,
    required this.evCompMin,
    required this.evCompMax,
    required this.evCompensationStep,
    required this.naturalStreamTextureId,
    required this.naturalStreamWidth,
    required this.naturalStreamHeight,
    required this.streamWidth,
    required this.streamHeight,
    required this.sensorStreamWidth,
    required this.sensorStreamHeight,
  });

  /// All supported YUV_420_888 stream resolutions, sorted descending by area.
  List<CamSize> supportedSizes;

  int isoMin;

  int isoMax;

  int exposureTimeMinNs;

  int exposureTimeMaxNs;

  double focusMin;

  double focusMax;

  double zoomMin;

  double zoomMax;

  int evCompMin;

  int evCompMax;

  double evCompensationStep;

  /// Flutter texture ID for the GPU natural stream (passthrough, no color adjustments).
  /// 0 if natural stream is disabled.
  int naturalStreamTextureId;

  /// Actual computed width of the GPU natural stream (pixels). 0 if natural stream is disabled.
  int naturalStreamWidth;

  /// Requested height of the GPU natural stream (pixels). 0 if natural stream is disabled.
  int naturalStreamHeight;

  /// Width of the GPU processed stream texture (pixels). Matches the largest 4:3 YUV size.
  int streamWidth;

  /// Height of the GPU processed stream texture (pixels).
  int streamHeight;

  /// Width of the camera session's YUV stream (the actual sensor output
  /// before any GPU crop). Unlike [streamWidth], this does NOT change when
  /// [CamSettings.cropOutputSize] is active — it always reports the
  /// Camera2 session's configured output size.
  int sensorStreamWidth;

  /// Height of the camera session's YUV stream. See [sensorStreamWidth].
  int sensorStreamHeight;

  Object encode() {
    return <Object?>[
      supportedSizes,
      isoMin,
      isoMax,
      exposureTimeMinNs,
      exposureTimeMaxNs,
      focusMin,
      focusMax,
      zoomMin,
      zoomMax,
      evCompMin,
      evCompMax,
      evCompensationStep,
      naturalStreamTextureId,
      naturalStreamWidth,
      naturalStreamHeight,
      streamWidth,
      streamHeight,
      sensorStreamWidth,
      sensorStreamHeight,
    ];
  }

  static CamCapabilities decode(Object result) {
    result as List<Object?>;
    return CamCapabilities(
      supportedSizes: (result[0] as List<Object?>?)!.cast<CamSize>(),
      isoMin: result[1]! as int,
      isoMax: result[2]! as int,
      exposureTimeMinNs: result[3]! as int,
      exposureTimeMaxNs: result[4]! as int,
      focusMin: result[5]! as double,
      focusMax: result[6]! as double,
      zoomMin: result[7]! as double,
      zoomMax: result[8]! as double,
      evCompMin: result[9]! as int,
      evCompMax: result[10]! as int,
      evCompensationStep: result[11]! as double,
      naturalStreamTextureId: result[12]! as int,
      naturalStreamWidth: result[13]! as int,
      naturalStreamHeight: result[14]! as int,
      streamWidth: result[15]! as int,
      streamHeight: result[16]! as int,
      sensorStreamWidth: result[17]! as int,
      sensorStreamHeight: result[18]! as int,
    );
  }
}

/// Lean payload for the active stream-configuration change callback.
///
/// Emitted on the active selection changing (after [CameraHostApi.setResolution]
/// resolves or after [CamSettings.cropOutputSize] is set/cleared) — distinct
/// from the heavier [CamCapabilities] which is a one-time bootstrap surface
/// retrieved via [CameraHostApi.getCapabilities].
///
/// The texture-ID fields ([naturalTextureId], [previewTextureId]) are stable
/// across the open session — they are minted at [CameraHostApi.open] time and
/// carried on every change emission so a Dart consumer never needs a
/// separate getCapabilities round-trip after a configuration change.
class CamStreamConfiguration {
  CamStreamConfiguration({
    required this.captureWidth,
    required this.captureHeight,
    this.cropWidth,
    this.cropHeight,
    required this.naturalTextureId,
    required this.previewTextureId,
  });

  /// Width of the active capture stream (sensor output before any GPU crop).
  int captureWidth;

  /// Height of the active capture stream.
  int captureHeight;

  /// Width of the active GPU center crop. Null = no crop (full capture).
  int? cropWidth;

  /// Height of the active GPU center crop. Null = no crop (full capture).
  int? cropHeight;

  /// Flutter texture ID for the natural-stream lane. Stable across the open session.
  int naturalTextureId;

  /// Flutter texture ID for the processed (post-color-pipeline) preview lane.
  /// Stable across the open session.
  int previewTextureId;

  Object encode() {
    return <Object?>[
      captureWidth,
      captureHeight,
      cropWidth,
      cropHeight,
      naturalTextureId,
      previewTextureId,
    ];
  }

  static CamStreamConfiguration decode(Object result) {
    result as List<Object?>;
    return CamStreamConfiguration(
      captureWidth: result[0]! as int,
      captureHeight: result[1]! as int,
      cropWidth: result[2] as int?,
      cropHeight: result[3] as int?,
      naturalTextureId: result[4]! as int,
      previewTextureId: result[5]! as int,
    );
  }
}

class CamStateUpdate {
  CamStateUpdate({
    required this.state,
  });

  /// One of: "closed", "opening", "streaming", "recovering", "error"
  String state;

  Object encode() {
    return <Object?>[
      state,
    ];
  }

  static CamStateUpdate decode(Object result) {
    result as List<Object?>;
    return CamStateUpdate(
      state: result[0]! as String,
    );
  }
}

class CamError {
  CamError({
    required this.code,
    required this.message,
    required this.isFatal,
  });

  CamErrorCode code;

  String message;

  bool isFatal;

  Object encode() {
    return <Object?>[
      code,
      message,
      isFatal,
    ];
  }

  static CamError decode(Object result) {
    result as List<Object?>;
    return CamError(
      code: result[0]! as CamErrorCode,
      message: result[1]! as String,
      isFatal: result[2]! as bool,
    );
  }
}

/// Actual sensor values reported by the hardware after each captured frame.
///
/// All fields are nullable — null means the hardware did not report that value.
/// Delivered via [CameraFlutterApi.onFrameResult] at ~3 Hz (every 10th frame).
class CamFrameResult {
  CamFrameResult({
    this.iso,
    this.exposureTimeNs,
    this.focusDistanceDiopters,
    this.wbGainR,
    this.wbGainG,
    this.wbGainB,
  });

  /// Actual sensor sensitivity (ISO) used for this frame.
  int? iso;

  /// Actual exposure duration in nanoseconds used for this frame.
  int? exposureTimeNs;

  /// Actual focus distance in diopters (1/metres). 0.0 = infinity.
  double? focusDistanceDiopters;

  /// Red channel gain from COLOR_CORRECTION_GAINS.
  double? wbGainR;

  /// Green channel gain (average of greenEven + greenOdd).
  double? wbGainG;

  /// Blue channel gain from COLOR_CORRECTION_GAINS.
  double? wbGainB;

  Object encode() {
    return <Object?>[
      iso,
      exposureTimeNs,
      focusDistanceDiopters,
      wbGainR,
      wbGainG,
      wbGainB,
    ];
  }

  static CamFrameResult decode(Object result) {
    result as List<Object?>;
    return CamFrameResult(
      iso: result[0] as int?,
      exposureTimeNs: result[1] as int?,
      focusDistanceDiopters: result[2] as double?,
      wbGainR: result[3] as double?,
      wbGainG: result[4] as double?,
      wbGainB: result[5] as double?,
    );
  }
}

/// Mean R, G, B from a sampled image patch. All values in [0.0, 1.0].
class CamRgbSample {
  CamRgbSample({
    required this.r,
    required this.g,
    required this.b,
  });

  double r;

  double g;

  double b;

  Object encode() {
    return <Object?>[
      r,
      g,
      b,
    ];
  }

  static CamRgbSample decode(Object result) {
    result as List<Object?>;
    return CamRgbSample(
      r: result[0]! as double,
      g: result[1]! as double,
      b: result[2]! as double,
    );
  }
}

/// Destination for image-capture output on iOS Photos / Android MediaStore.
///
/// When [saveToLibrary] is true: iOS writes through PHPhotoLibrary and yields
/// a PHAsset local identifier (no filesystem path); Android writes through
/// MediaStore and yields a content URI / file path. When false: both
/// platforms write to filesystem at the [CameraHostApi.captureImage]
/// `outputDirectory` + `fileName` arguments and yield the filesystem path.
class CamPhotosDestination {
  CamPhotosDestination({
    this.albumName,
    required this.saveToLibrary,
  });

  /// Optional album name on iOS Photos. Ignored on Android.
  String? albumName;

  /// If true, save to the platform photo library (Photos / MediaStore).
  /// If false, write to filesystem at the host method's outputDirectory + fileName.
  bool saveToLibrary;

  Object encode() {
    return <Object?>[
      albumName,
      saveToLibrary,
    ];
  }

  static CamPhotosDestination decode(Object result) {
    result as List<Object?>;
    return CamPhotosDestination(
      albumName: result[0] as String?,
      saveToLibrary: result[1]! as bool,
    );
  }
}

/// Result of an image capture.
///
/// One of [filePath] / [phAssetLocalId] is non-null depending on the
/// [CamPhotosDestination.saveToLibrary] flag and platform:
/// - iOS + saveToLibrary == true: [phAssetLocalId] populated; [filePath] null.
/// - iOS + saveToLibrary == false (or null destination): [filePath] populated.
/// - Android (any destination): [filePath] populated; [phAssetLocalId] null.
class CamCaptureResult {
  CamCaptureResult({
    this.filePath,
    this.phAssetLocalId,
  });

  String? filePath;

  String? phAssetLocalId;

  Object encode() {
    return <Object?>[
      filePath,
      phAssetLocalId,
    ];
  }

  static CamCaptureResult decode(Object result) {
    result as List<Object?>;
    return CamCaptureResult(
      filePath: result[0] as String?,
      phAssetLocalId: result[1] as String?,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is CamErrorCode) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is CamSize) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is CamSettings) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is CamProcessingParams) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is CamCapabilities) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is CamStreamConfiguration) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is CamStateUpdate) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is CamError) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is CamFrameResult) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is CamRgbSample) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is CamPhotosDestination) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    }    else if (value is CamCaptureResult) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : CamErrorCode.values[value];
      case 130: 
        return CamSize.decode(readValue(buffer)!);
      case 131: 
        return CamSettings.decode(readValue(buffer)!);
      case 132: 
        return CamProcessingParams.decode(readValue(buffer)!);
      case 133: 
        return CamCapabilities.decode(readValue(buffer)!);
      case 134: 
        return CamStreamConfiguration.decode(readValue(buffer)!);
      case 135: 
        return CamStateUpdate.decode(readValue(buffer)!);
      case 136: 
        return CamError.decode(readValue(buffer)!);
      case 137: 
        return CamFrameResult.decode(readValue(buffer)!);
      case 138: 
        return CamRgbSample.decode(readValue(buffer)!);
      case 139: 
        return CamPhotosDestination.decode(readValue(buffer)!);
      case 140: 
        return CamCaptureResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class CameraHostApi {
  /// Constructor for [CameraHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  CameraHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<int> open(String? cameraId, CamSettings? settings) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_camera.CameraHostApi.open$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[cameraId, settings]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as int?)!;
    }
  }

  Future<CamCapabilities> getCapabilities(int handle) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_camera.CameraHostApi.getCapabilities$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[handle]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as CamCapabilities?)!;
    }
  }

  Future<void> updateSettings(int handle, CamSettings settings) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_camera.CameraHostApi.updateSettings$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[handle, settings]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setResolution(int handle, int width, int height) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_camera.CameraHostApi.setResolution$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[handle, width, height]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setProcessingParams(int handle, CamProcessingParams params) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_camera.CameraHostApi.setProcessingParams$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[handle, params]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Captures a still JPEG image using Camera2's hardware ISP (Android) or
  /// the natural-lane tap (iOS). Does NOT include GPU post-processing
  /// (saturation, contrast, brightness, black balance, gamma).
  ///
  /// Returns a [CamCaptureResult] whose populated field depends on
  /// [destination] and platform — see [CamPhotosDestination] /
  /// [CamCaptureResult] for the per-platform semantics.
  Future<CamCaptureResult> captureNaturalPicture(int handle, String? outputDirectory, String? fileName, CamPhotosDestination? destination) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_camera.CameraHostApi.captureNaturalPicture$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[handle, outputDirectory, fileName, destination]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as CamCaptureResult?)!;
    }
  }

  /// Captures the next GPU post-processed frame and saves it.
  /// Format is inferred from [fileName] extension: .jpg/.jpeg → JPEG (quality 90),
  /// .png or absent extension → PNG. [outputDirectory] null = system gallery
  /// under Pictures/CambrianCamera (via MediaStore on Android).
  ///
  /// Returns a [CamCaptureResult] whose populated field depends on
  /// [destination] and platform — see [CamPhotosDestination] /
  /// [CamCaptureResult] for the per-platform semantics.
  Future<CamCaptureResult> captureImage(int handle, String? outputDirectory, String? fileName, CamPhotosDestination? destination) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_camera.CameraHostApi.captureImage$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[handle, outputDirectory, fileName, destination]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as CamCaptureResult?)!;
    }
  }

  Future<int?> getNativePipelineHandle(int handle) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_camera.CameraHostApi.getNativePipelineHandle$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[handle]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as int?);
    }
  }

  Future<String> startRecording(int handle, String? outputDirectory, String? fileName, int? bitrate, int? fps) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_camera.CameraHostApi.startRecording$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[handle, outputDirectory, fileName, bitrate, fps]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<String> stopRecording(int handle) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_camera.CameraHostApi.stopRecording$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[handle]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<void> close(int handle) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_camera.CameraHostApi.close$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[handle]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> pause(int handle) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_camera.CameraHostApi.pause$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[handle]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> resume(int handle) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_camera.CameraHostApi.resume$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[handle]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Returns persisted processing params from a previous session, or null if none exist.
  ///
  /// Dart should call this after [open] to initialize slider UI with the user's last-known
  /// values instead of sending default zeros that would overwrite the persisted state.
  Future<CamProcessingParams?> getPersistedProcessingParams(int handle) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_camera.CameraHostApi.getPersistedProcessingParams$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[handle]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as CamProcessingParams?);
    }
  }

  /// Samples the center 96×96 pixel patch of the most recent GPU-processed
  /// RGBA frame and returns the trimmed-mean R, G, B as values in [0.0, 1.0].
  ///
  /// Throws with error code "patch_not_ready" if no frame has been rendered yet.
  Future<CamRgbSample> sampleCenterPatch(int handle) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cambrian_camera.CameraHostApi.sampleCenterPatch$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[handle]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as CamRgbSample?)!;
    }
  }
}

abstract class CameraFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onStateChanged(int handle, CamStateUpdate state);

  void onError(int handle, CamError error);

  void onFrameResult(int handle, CamFrameResult result);

  /// Called when the recording state changes.
  /// [state] is one of: "recording", "idle", "error".
  void onRecordingStateChanged(int handle, String state);

  /// Called when the active stream configuration changes — after
  /// `cropOutputSize` is set or cleared, or after `setResolution` resolves
  /// to a new camera stream size. The payload's texture-ID fields are
  /// stable across the open session and are repeated on every change so
  /// Dart consumers do not need a separate `getCapabilities` round-trip.
  void onStreamConfigurationChanged(int handle, CamStreamConfiguration configuration);

  static void setUp(CameraFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onStateChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onStateChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_handle = (args[0] as int?);
          assert(arg_handle != null,
              'Argument for dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onStateChanged was null, expected non-null int.');
          final CamStateUpdate? arg_state = (args[1] as CamStateUpdate?);
          assert(arg_state != null,
              'Argument for dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onStateChanged was null, expected non-null CamStateUpdate.');
          try {
            api.onStateChanged(arg_handle!, arg_state!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onError$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onError was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_handle = (args[0] as int?);
          assert(arg_handle != null,
              'Argument for dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onError was null, expected non-null int.');
          final CamError? arg_error = (args[1] as CamError?);
          assert(arg_error != null,
              'Argument for dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onError was null, expected non-null CamError.');
          try {
            api.onError(arg_handle!, arg_error!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onFrameResult$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onFrameResult was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_handle = (args[0] as int?);
          assert(arg_handle != null,
              'Argument for dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onFrameResult was null, expected non-null int.');
          final CamFrameResult? arg_result = (args[1] as CamFrameResult?);
          assert(arg_result != null,
              'Argument for dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onFrameResult was null, expected non-null CamFrameResult.');
          try {
            api.onFrameResult(arg_handle!, arg_result!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onRecordingStateChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onRecordingStateChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_handle = (args[0] as int?);
          assert(arg_handle != null,
              'Argument for dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onRecordingStateChanged was null, expected non-null int.');
          final String? arg_state = (args[1] as String?);
          assert(arg_state != null,
              'Argument for dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onRecordingStateChanged was null, expected non-null String.');
          try {
            api.onRecordingStateChanged(arg_handle!, arg_state!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onStreamConfigurationChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onStreamConfigurationChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_handle = (args[0] as int?);
          assert(arg_handle != null,
              'Argument for dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onStreamConfigurationChanged was null, expected non-null int.');
          final CamStreamConfiguration? arg_configuration = (args[1] as CamStreamConfiguration?);
          assert(arg_configuration != null,
              'Argument for dev.flutter.pigeon.cambrian_camera.CameraFlutterApi.onStreamConfigurationChanged was null, expected non-null CamStreamConfiguration.');
          try {
            api.onStreamConfigurationChanged(arg_handle!, arg_configuration!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
